<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Page_switching</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="main_page.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="S7netplus" Version="0.20.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="InduLink.Abstractions">
      <HintPath>..\..\Total\InduLink.Protocols.S7\bin\Debug\net8.0\InduLink.Abstractions.dll</HintPath>
    </Reference>
    <Reference Include="InduLink.Protocols.S7">
      <HintPath>..\..\Total\InduLink.Protocols.S7\bin\Debug\net8.0\InduLink.Protocols.S7.dll</HintPath>
    </Reference>
    <Reference Include="InduLink.Runtime">
      <HintPath>..\..\Total\InduLink.Protocols.S7\bin\Debug\net8.0\InduLink.Runtime.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="App.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
