<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Page_switching</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="main_page.cs">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\Total\InduLink.Protocols.Ads\InduLink.Protocols.Ads.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="InduLink.Protocols.Ads.Router">
      <HintPath>..\..\Total\InduLink.Protocols.Ads.Router\bin\Debug\net8.0\InduLink.Protocols.Ads.Router.dll</HintPath>
    </Reference>
    <Reference Include="LogHelper">
      <HintPath>..\..\Total\LogHelper\bin\Release\net472\LogHelper.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="App.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
