<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Page_switching</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Forms\main_page.cs">
      <SubType>Form</SubType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <TargetPath>main_page.cs</TargetPath>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="panel\*.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="panel\*.Designer.cs">
      <SubType>Code</SubType>
      <DependentUpon>$([System.String]::Copy('%(Filename)').Replace('.Designer', '')).cs</DependentUpon>
    </Compile>
    <EmbeddedResource Update="panel\*.resx">
      <DependentUpon>%(Filename).cs</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="8.0.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\Total\InduLink.Protocols.Ads\InduLink.Protocols.Ads.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="InduLink.Storage">
      <HintPath>..\..\Total\InduLink.Storage\bin\Release\net8.0\InduLink.Storage.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="InduLink.Abstractions">
      <HintPath>..\..\Total\InduLink.Storage\bin\Release\net8.0\InduLink.Abstractions.dll</HintPath>
      <Private>true</Private>
    </Reference>
    <Reference Include="InduLink.Protocols.Ads.Router">
      <HintPath>..\..\Total\InduLink.Protocols.Ads.Router\bin\Debug\net8.0\InduLink.Protocols.Ads.Router.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="App.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
