namespace Page_switching.panel;

partial class Calibration
{
    private Panel pagePanel;

    private void InitializeComponent()
    {
        pagePanel = new Panel();
        root = new TableLayoutPanel();
        title = new Label();
        toolbar = new TableLayoutPanel();
        sensorControls = new FlowLayoutPanel();
        pointActions = new FlowLayoutPanel();
        channelCaption = new Label();
        channelPicker = new ComboBox();
        rawCaption = new Label();
        rawValue = new Label();
        zeroButton = new Button();
        addButton = new Button();
        removeButton = new Button();
        fitButton = new Button();
        saveButton = new Button();
        importButton = new Button();
        exportButton = new Button();
        batchButton = new Button();
        pointsGrid = new DataGridView();
        rawColumn = new DataGridViewTextBoxColumn();
        levelColumn = new DataGridViewTextBoxColumn();
        result = new Label();
        ((System.ComponentModel.ISupportInitialize)pointsGrid).BeginInit();
        SuspendLayout();
        batchButton.Name = "batchButton";
        batchButton.Text = "批量标定";
        batchButton.Size = new Size(105, 34);
        batchButton.FlatStyle = FlatStyle.Flat;
        batchButton.BackColor = Color.FromArgb(248, 250, 252);
        batchButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
        pointActions.Controls.Add(batchButton);

        root.BackColor = Color.FromArgb(241, 245, 249);
        root.ColumnCount = 1;
        root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        root.Dock = DockStyle.Fill;
        root.Padding = new Padding(16);
        root.RowCount = 4;

        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 106F));
        root.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 60F));
        root.Name = "root";
        root.AutoScroll = false;

        title.Dock = DockStyle.Fill;
        title.Font = new Font("Microsoft YaHei UI", 16F, FontStyle.Bold);
        title.ForeColor = Color.FromArgb(15, 23, 42);
        title.Text = "传感器标定";
        title.Name = "title";
        root.Controls.Add(title, 0, 0);

        toolbar.BackColor = Color.White;

        toolbar.Dock = DockStyle.Fill;
        toolbar.Padding = new Padding(12, 8, 12, 8);
        toolbar.Name = "toolbar";
        toolbar.RowCount = 2;
        toolbar.ColumnCount = 1;


        root.Controls.Add(toolbar, 0, 1);
        toolbar.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        toolbar.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
        toolbar.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        sensorControls.Dock = DockStyle.Fill;
        sensorControls.Margin = new Padding(0);
        sensorControls.Name = "sensorControls";
        sensorControls.WrapContents = false;
        pointActions.Dock = DockStyle.Fill;
        pointActions.Margin = new Padding(0);
        pointActions.Name = "pointActions";
        pointActions.AutoScroll = true;
        pointActions.WrapContents = false;
        toolbar.Controls.Add(sensorControls, 0, 0);
        toolbar.Controls.Add(pointActions, 0, 1);
        channelCaption.AutoSize = true;
        channelCaption.Margin = new Padding(0, 12, 5, 0);
        channelCaption.Text = "通道";
        channelCaption.Name = "channelCaption";
        sensorControls.Controls.Add(channelCaption);
        channelPicker.DropDownStyle = ComboBoxStyle.DropDownList;
        channelPicker.BackColor = Color.White;
        channelPicker.ForeColor = Color.FromArgb(15, 23, 42);
        channelPicker.Name = "channelPicker";
        channelPicker.FlatStyle = FlatStyle.Flat;
        channelPicker.Size = new Size(92, 30);
        sensorControls.Controls.Add(channelPicker);
        rawCaption.AutoSize = true;
        rawCaption.Margin = new Padding(15, 12, 5, 0);
        rawCaption.Text = "当前原始值";
        rawCaption.Name = "rawCaption";
        sensorControls.Controls.Add(rawCaption);
        rawValue.AutoSize = false;
        rawValue.ForeColor = Color.FromArgb(15, 23, 42);
        rawValue.Margin = new Padding(0, 7, 10, 0);
        rawValue.Name = "rawValue";
        rawValue.Font = new Font("Microsoft YaHei UI", 11F, FontStyle.Bold);
        rawValue.Size = new Size(85, 32);
        rawValue.Text = "--";
        rawValue.TextAlign = ContentAlignment.MiddleLeft;
        sensorControls.Controls.Add(rawValue);
        zeroButton.BackColor = Color.FromArgb(248, 250, 252);
        zeroButton.FlatAppearance.BorderSize = 1;
        zeroButton.FlatStyle = FlatStyle.Flat;
        zeroButton.ForeColor = Color.FromArgb(15, 23, 42);
        zeroButton.Font = new Font("Microsoft YaHei UI", 9F);
        zeroButton.Margin = new Padding(0, 2, 8, 0);
        zeroButton.Name = "zeroButton";
        zeroButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(226, 232, 240);
        zeroButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
        zeroButton.Cursor = Cursors.Hand;
        zeroButton.Size = new Size(106, 36);
        zeroButton.Text = "当前值定零";
        zeroButton.UseVisualStyleBackColor = false;
        pointActions.Controls.Add(zeroButton);
        addButton.BackColor = Color.FromArgb(248, 250, 252);
        addButton.FlatAppearance.BorderSize = 1;
        addButton.FlatStyle = FlatStyle.Flat;
        addButton.ForeColor = Color.FromArgb(15, 23, 42);
        addButton.Font = new Font("Microsoft YaHei UI", 9F);
        addButton.Margin = new Padding(0, 2, 8, 0);
        addButton.Name = "addButton";
        addButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(226, 232, 240);
        addButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
        addButton.Cursor = Cursors.Hand;
        addButton.Size = new Size(106, 36);
        addButton.Text = "添加标定点";
        addButton.UseVisualStyleBackColor = false;
        pointActions.Controls.Add(addButton);
        removeButton.BackColor = Color.FromArgb(248, 250, 252);
        removeButton.FlatAppearance.BorderSize = 1;
        removeButton.FlatStyle = FlatStyle.Flat;
        removeButton.ForeColor = Color.FromArgb(15, 23, 42);
        removeButton.Font = new Font("Microsoft YaHei UI", 9F);
        removeButton.Margin = new Padding(0, 2, 8, 0);
        removeButton.Name = "removeButton";
        removeButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(226, 232, 240);
        removeButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
        removeButton.Cursor = Cursors.Hand;
        removeButton.Size = new Size(106, 36);
        removeButton.Text = "删除选中点";
        removeButton.UseVisualStyleBackColor = false;
        pointActions.Controls.Add(removeButton);
        fitButton.BackColor = Color.FromArgb(248, 250, 252);
        fitButton.FlatAppearance.BorderSize = 1;
        fitButton.FlatStyle = FlatStyle.Flat;
        fitButton.ForeColor = Color.FromArgb(15, 23, 42);
        fitButton.Font = new Font("Microsoft YaHei UI", 9F);
        fitButton.Margin = new Padding(0, 2, 8, 0);
        fitButton.Name = "fitButton";
        fitButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(226, 232, 240);
        fitButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
        fitButton.Cursor = Cursors.Hand;
        fitButton.Size = new Size(100, 36);
        fitButton.Text = "计算系数";
        fitButton.UseVisualStyleBackColor = false;
        pointActions.Controls.Add(fitButton);
        saveButton.BackColor = Color.FromArgb(29, 78, 216);
        saveButton.FlatAppearance.BorderSize = 0;
        saveButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(30, 64, 175);
        saveButton.FlatStyle = FlatStyle.Flat;
        saveButton.ForeColor = Color.White;
        saveButton.Font = new Font("Microsoft YaHei UI", 9F);
        saveButton.Margin = new Padding(0, 2, 8, 0);
        saveButton.Name = "saveButton";
        saveButton.Cursor = Cursors.Hand;
        saveButton.Size = new Size(100, 36);
        saveButton.Text = "保存标定";
        saveButton.UseVisualStyleBackColor = false;
        pointActions.Controls.Add(saveButton);
        importButton.BackColor = Color.FromArgb(248, 250, 252);
        importButton.FlatAppearance.BorderSize = 1;
        importButton.FlatStyle = FlatStyle.Flat;
        importButton.ForeColor = Color.FromArgb(15, 23, 42);
        importButton.Font = new Font("Microsoft YaHei UI", 9F);
        importButton.Margin = new Padding(0, 2, 8, 0);
        importButton.Name = "importButton";
        importButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(226, 232, 240);
        importButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
        importButton.Cursor = Cursors.Hand;
        importButton.Size = new Size(100, 36);
        importButton.Text = "导入 .conf";
        importButton.UseVisualStyleBackColor = false;
        pointActions.Controls.Add(importButton);
        exportButton.BackColor = Color.FromArgb(248, 250, 252);
        exportButton.FlatAppearance.BorderSize = 1;
        exportButton.FlatStyle = FlatStyle.Flat;
        exportButton.ForeColor = Color.FromArgb(15, 23, 42);
        exportButton.Font = new Font("Microsoft YaHei UI", 9F);
        exportButton.Margin = new Padding(0, 2, 8, 0);
        exportButton.Name = "exportButton";
        exportButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(226, 232, 240);
        exportButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
        exportButton.Cursor = Cursors.Hand;
        exportButton.Size = new Size(100, 36);
        exportButton.Text = "导出 .conf";
        exportButton.UseVisualStyleBackColor = false;
        pointActions.Controls.Add(exportButton);

        pointsGrid.AllowUserToAddRows = true;
        pointsGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        pointsGrid.BackgroundColor = Color.White;
        pointsGrid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(248, 250, 252);
        pointsGrid.ColumnHeadersDefaultCellStyle.ForeColor = Color.FromArgb(15, 23, 42);
        pointsGrid.DefaultCellStyle.BackColor = Color.White;
        pointsGrid.DefaultCellStyle.ForeColor = Color.FromArgb(15, 23, 42);
        pointsGrid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(219, 234, 254);
        pointsGrid.DefaultCellStyle.SelectionForeColor = Color.FromArgb(15, 23, 42);
        pointsGrid.EnableHeadersVisualStyles = false;
        pointsGrid.GridColor = Color.FromArgb(226, 232, 240);
        pointsGrid.RowHeadersDefaultCellStyle.BackColor = Color.FromArgb(241, 245, 249);
        pointsGrid.RowHeadersDefaultCellStyle.ForeColor = Color.FromArgb(15, 23, 42);
        pointsGrid.RowHeadersDefaultCellStyle.SelectionBackColor = Color.FromArgb(219, 234, 254);
        pointsGrid.RowHeadersDefaultCellStyle.SelectionForeColor = Color.FromArgb(15, 23, 42);
        pointsGrid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        pointsGrid.Columns.AddRange(rawColumn, levelColumn);
        pointsGrid.Dock = DockStyle.Fill;
        pointsGrid.Margin = new Padding(0, 10, 0, 10);
        pointsGrid.Name = "pointsGrid";
        pointsGrid.ColumnHeadersDefaultCellStyle.SelectionForeColor = Color.FromArgb(15, 23, 42);
        pointsGrid.ColumnHeadersDefaultCellStyle.SelectionBackColor = Color.FromArgb(248, 250, 252);
        pointsGrid.AllowUserToResizeRows = false;
        pointsGrid.RowTemplate.Height = 30;
        pointsGrid.RowHeadersVisible = false;
        pointsGrid.AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(248, 250, 252);
        pointsGrid.DefaultCellStyle.Padding = new Padding(8, 0, 8, 0);
        pointsGrid.ColumnHeadersHeight = 36;
        pointsGrid.ColumnHeadersDefaultCellStyle.Font = new Font("Microsoft YaHei UI", 9F, FontStyle.Bold);
        pointsGrid.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
        pointsGrid.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
        pointsGrid.BorderStyle = BorderStyle.None;
        pointsGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        rawColumn.HeaderText = "原始计数";
        rawColumn.Name = "rawColumn";
        levelColumn.HeaderText = "标定水位 (mm)";
        levelColumn.Name = "levelColumn";
        root.Controls.Add(pointsGrid, 0, 2);

        result.BackColor = Color.White;
        result.BorderStyle = BorderStyle.None;
        result.Dock = DockStyle.Fill;
        result.Font = new Font("Microsoft YaHei UI", 9F);
        result.ForeColor = Color.FromArgb(71, 85, 105);
        result.Padding = new Padding(14);
        result.Name = "result";
        result.AutoEllipsis = true;
        result.Text = "先录入至少两个不同原始计数的标定点，再计算并保存。";
        root.Controls.Add(result, 0, 3);

        BackColor = Color.FromArgb(241, 245, 249);
        ForeColor = Color.FromArgb(15, 23, 42);
        pagePanel.Name = "pagePanel";
        pagePanel.Dock = DockStyle.Fill;
        pagePanel.Controls.Add(root);
        Name = "Calibration";
        Controls.Add(pagePanel);
        Size = new Size(1104, 606);
        Font = new Font("Microsoft YaHei UI", 9F);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        AutoScroll = true;
        AutoScrollMinSize = new Size(860, 530);
        ((System.ComponentModel.ISupportInitialize)pointsGrid).EndInit();
        ResumeLayout(false);
    }


    private TableLayoutPanel root;
    private Label title;
    private TableLayoutPanel toolbar;
    private FlowLayoutPanel sensorControls;
    private FlowLayoutPanel pointActions;
    private Label channelCaption;
    private ComboBox channelPicker;
    private Label rawCaption;
    private Label rawValue;
    private Button zeroButton;
    private Button addButton;
    private Button removeButton;
    private Button fitButton;
    private Button saveButton;
    private Button importButton;
    private Button exportButton;
    private Button batchButton;
    private DataGridView pointsGrid;
    private DataGridViewTextBoxColumn rawColumn;
    private DataGridViewTextBoxColumn levelColumn;
    private Label result;
}
