namespace Page_switching.panel
{
    partial class CustomSpectrumPage
    {
        private System.ComponentModel.IContainer components = null;
        private Panel pagePanel;
        private TableLayoutPanel root;
        private GroupBox parameterGroup;
        private TableLayoutPanel options;
        private GroupBox previewGroup;
        private Label status;
        private TextBox spectrumPath;
        private Button spectrumBrowse;
        private TextBox outputPath;
        private Button outputBrowse;
        private NumericUpDown depthInput;
        private NumericUpDown stepInput;
        private NumericUpDown countInput;
        private NumericUpDown seedInput;
        private NumericUpDown frequencyInput;
        private NumericUpDown periodInput;
        private NumericUpDown angleInput;
        private ComboBox theoryInput;
        private ComboBox sideInput;
        private ComboBox modeInput;
        private CheckBox absorbInput;
        private Button runButton;
        private Button previewButton;
        private Label caption_spectrumPath;
        private Label caption_outputPath;
        private Label caption_depthInput;
        private Label caption_stepInput;
        private Label caption_countInput;
        private Label caption_seedInput;
        private Label caption_frequencyInput;
        private Label caption_periodInput;
        private Label caption_angleInput;
        private Label caption_theoryInput;
        private Label caption_sideInput;
        private Label caption_modeInput;
        private ComparisonPlotControl plot;

        protected override void Dispose(bool disposing)
        {
            if (disposing) components?.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            pagePanel = new Panel();
            root = new TableLayoutPanel();
            parameterGroup = new GroupBox();
            options = new TableLayoutPanel();
            previewGroup = new GroupBox();
            status = new Label();
            spectrumPath = new TextBox();
            spectrumBrowse = new Button();
            outputPath = new TextBox();
            outputBrowse = new Button();
            depthInput = new NumericUpDown();
            stepInput = new NumericUpDown();
            countInput = new NumericUpDown();
            seedInput = new NumericUpDown();
            frequencyInput = new NumericUpDown();
            periodInput = new NumericUpDown();
            angleInput = new NumericUpDown();
            theoryInput = new ComboBox();
            sideInput = new ComboBox();
            modeInput = new ComboBox();
            absorbInput = new CheckBox();
            runButton = new Button();
            previewButton = new Button();
            caption_spectrumPath = new Label();
            caption_outputPath = new Label();
            caption_depthInput = new Label();
            caption_stepInput = new Label();
            caption_countInput = new Label();
            caption_seedInput = new Label();
            caption_frequencyInput = new Label();
            caption_periodInput = new Label();
            caption_angleInput = new Label();
            caption_theoryInput = new Label();
            caption_sideInput = new Label();
            caption_modeInput = new Label();
            plot = new ComparisonPlotControl();
            ((System.ComponentModel.ISupportInitialize)depthInput).BeginInit();
            ((System.ComponentModel.ISupportInitialize)stepInput).BeginInit();
            ((System.ComponentModel.ISupportInitialize)countInput).BeginInit();
            ((System.ComponentModel.ISupportInitialize)seedInput).BeginInit();
            ((System.ComponentModel.ISupportInitialize)frequencyInput).BeginInit();
            ((System.ComponentModel.ISupportInitialize)periodInput).BeginInit();
            ((System.ComponentModel.ISupportInitialize)angleInput).BeginInit();
            pagePanel.SuspendLayout();
            root.SuspendLayout();
            parameterGroup.SuspendLayout();
            options.SuspendLayout();
            previewGroup.SuspendLayout();
            SuspendLayout();

            // 与规则波、不规则波一致：左侧参数，右侧预览。
            pagePanel.Name = "pagePanel";
            root.Name = "root";
            parameterGroup.Name = "parameterGroup";
            options.Name = "options";
            previewGroup.Name = "previewGroup";
            status.Name = "status";
            spectrumPath.Name = "spectrumPath";
            spectrumBrowse.Name = "spectrumBrowse";
            outputPath.Name = "outputPath";
            outputBrowse.Name = "outputBrowse";
            depthInput.Name = "depthInput";
            stepInput.Name = "stepInput";
            countInput.Name = "countInput";
            seedInput.Name = "seedInput";
            frequencyInput.Name = "frequencyInput";
            periodInput.Name = "periodInput";
            angleInput.Name = "angleInput";
            theoryInput.Name = "theoryInput";
            sideInput.Name = "sideInput";
            modeInput.Name = "modeInput";
            absorbInput.Name = "absorbInput";
            runButton.Name = "runButton";
            previewButton.Name = "previewButton";
            caption_spectrumPath.Name = "caption_spectrumPath";
            caption_outputPath.Name = "caption_outputPath";
            caption_depthInput.Name = "caption_depthInput";
            caption_stepInput.Name = "caption_stepInput";
            caption_countInput.Name = "caption_countInput";
            caption_seedInput.Name = "caption_seedInput";
            caption_frequencyInput.Name = "caption_frequencyInput";
            caption_periodInput.Name = "caption_periodInput";
            caption_angleInput.Name = "caption_angleInput";
            caption_theoryInput.Name = "caption_theoryInput";
            caption_sideInput.Name = "caption_sideInput";
            caption_modeInput.Name = "caption_modeInput";
            plot.Name = "plot";
            pagePanel.Dock = DockStyle.Fill;
            pagePanel.Padding = new Padding(8);
            pagePanel.Controls.Add(root);
            root.Dock = DockStyle.Fill;
            root.ColumnCount = 2;
            root.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 480F));
            root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            root.RowCount = 1;
            root.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            root.MinimumSize = new Size(930, 460);
            root.Controls.Add(parameterGroup, 0, 0);
            root.Controls.Add(previewGroup, 1, 0);
            parameterGroup.Dock = DockStyle.Fill;
            parameterGroup.BackColor = Color.White;
            parameterGroup.Font = new Font("Microsoft YaHei UI", 9F, FontStyle.Bold);
            parameterGroup.ForeColor = Color.FromArgb(15, 23, 42);
            parameterGroup.Padding = new Padding(10, 16, 10, 10);
            parameterGroup.TabStop = false;
            parameterGroup.Text = "自定义谱参数";
            previewGroup.Dock = DockStyle.Fill;
            previewGroup.BackColor = Color.White;
            previewGroup.Font = new Font("Microsoft YaHei UI", 9F, FontStyle.Bold);
            previewGroup.ForeColor = Color.FromArgb(15, 23, 42);
            previewGroup.Padding = new Padding(10, 18, 10, 10);
            previewGroup.TabStop = false;
            previewGroup.Text = "波谱与波形预览";
            parameterGroup.Controls.Add(options);
            previewGroup.Controls.Add(plot);

            // 固定行列对齐，路径和操作按钮使用与另外两页相同的样式。
            options.Dock = DockStyle.Top;
            options.AutoSize = true;
            options.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            options.ColumnCount = 4;
            options.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 100F));
            options.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 115F));
            options.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 100F));
            options.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            options.RowCount = 10;
            options.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
            options.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
            options.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
            options.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
            options.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
            options.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
            options.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
            options.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
            options.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
            options.RowStyles.Add(new RowStyle(SizeType.Absolute, 60F));
            options.Controls.Add(caption_modeInput, 0, 0);
            options.Controls.Add(modeInput, 1, 0);
            options.Controls.Add(caption_theoryInput, 2, 0);
            options.Controls.Add(theoryInput, 3, 0);
            options.Controls.Add(caption_sideInput, 0, 1);
            options.Controls.Add(sideInput, 1, 1);
            options.Controls.Add(caption_angleInput, 2, 1);
            options.Controls.Add(angleInput, 3, 1);
            options.Controls.Add(caption_depthInput, 0, 2);
            options.Controls.Add(depthInput, 1, 2);
            options.Controls.Add(caption_stepInput, 2, 2);
            options.Controls.Add(stepInput, 3, 2);
            options.Controls.Add(caption_countInput, 0, 3);
            options.Controls.Add(countInput, 1, 3);
            options.Controls.Add(caption_seedInput, 2, 3);
            options.Controls.Add(seedInput, 3, 3);
            options.Controls.Add(caption_frequencyInput, 0, 4);
            options.Controls.Add(frequencyInput, 1, 4);
            options.Controls.Add(caption_periodInput, 2, 4);
            options.Controls.Add(periodInput, 3, 4);
            options.Controls.Add(absorbInput, 0, 5);
            options.SetColumnSpan(absorbInput, 4);
            options.Controls.Add(caption_spectrumPath, 0, 6);
            options.Controls.Add(spectrumPath, 1, 6);
            options.SetColumnSpan(spectrumPath, 2);
            options.Controls.Add(spectrumBrowse, 3, 6);
            options.Controls.Add(caption_outputPath, 0, 7);
            options.Controls.Add(outputPath, 1, 7);
            options.SetColumnSpan(outputPath, 2);
            options.Controls.Add(outputBrowse, 3, 7);
            options.Controls.Add(runButton, 0, 8);
            options.SetColumnSpan(runButton, 2);
            options.Controls.Add(previewButton, 2, 8);
            options.SetColumnSpan(previewButton, 2);
            options.Controls.Add(status, 0, 9);
            options.SetColumnSpan(status, 4);
            caption_spectrumPath.Text = "输入谱(.dat)";
            caption_spectrumPath.Dock = DockStyle.Fill;
            caption_spectrumPath.Font = new Font("Microsoft YaHei UI", 8.5F);
            caption_spectrumPath.ForeColor = Color.FromArgb(71, 85, 105);
            caption_spectrumPath.TextAlign = ContentAlignment.MiddleLeft;
            caption_outputPath.Text = "保存文件";
            caption_outputPath.Dock = DockStyle.Fill;
            caption_outputPath.Font = new Font("Microsoft YaHei UI", 8.5F);
            caption_outputPath.ForeColor = Color.FromArgb(71, 85, 105);
            caption_outputPath.TextAlign = ContentAlignment.MiddleLeft;
            caption_depthInput.Text = "水深(m)";
            caption_depthInput.Dock = DockStyle.Fill;
            caption_depthInput.Font = new Font("Microsoft YaHei UI", 8.5F);
            caption_depthInput.ForeColor = Color.FromArgb(71, 85, 105);
            caption_depthInput.TextAlign = ContentAlignment.MiddleLeft;
            caption_stepInput.Text = "步长(s)";
            caption_stepInput.Dock = DockStyle.Fill;
            caption_stepInput.Font = new Font("Microsoft YaHei UI", 8.5F);
            caption_stepInput.ForeColor = Color.FromArgb(71, 85, 105);
            caption_stepInput.TextAlign = ContentAlignment.MiddleLeft;
            caption_countInput.Text = "采样点数";
            caption_countInput.Dock = DockStyle.Fill;
            caption_countInput.Font = new Font("Microsoft YaHei UI", 8.5F);
            caption_countInput.ForeColor = Color.FromArgb(71, 85, 105);
            caption_countInput.TextAlign = ContentAlignment.MiddleLeft;
            caption_seedInput.Text = "随机种子";
            caption_seedInput.Dock = DockStyle.Fill;
            caption_seedInput.Font = new Font("Microsoft YaHei UI", 8.5F);
            caption_seedInput.ForeColor = Color.FromArgb(71, 85, 105);
            caption_seedInput.TextAlign = ContentAlignment.MiddleLeft;
            caption_frequencyInput.Text = "特征频率(Hz)";
            caption_frequencyInput.Dock = DockStyle.Fill;
            caption_frequencyInput.Font = new Font("Microsoft YaHei UI", 8.5F);
            caption_frequencyInput.ForeColor = Color.FromArgb(71, 85, 105);
            caption_frequencyInput.TextAlign = ContentAlignment.MiddleLeft;
            caption_periodInput.Text = "特征周期(s)";
            caption_periodInput.Dock = DockStyle.Fill;
            caption_periodInput.Font = new Font("Microsoft YaHei UI", 8.5F);
            caption_periodInput.ForeColor = Color.FromArgb(71, 85, 105);
            caption_periodInput.TextAlign = ContentAlignment.MiddleLeft;
            caption_angleInput.Text = "波向偏角";
            caption_angleInput.Dock = DockStyle.Fill;
            caption_angleInput.Font = new Font("Microsoft YaHei UI", 8.5F);
            caption_angleInput.ForeColor = Color.FromArgb(71, 85, 105);
            caption_angleInput.TextAlign = ContentAlignment.MiddleLeft;
            caption_theoryInput.Text = "造波理论";
            caption_theoryInput.Dock = DockStyle.Fill;
            caption_theoryInput.Font = new Font("Microsoft YaHei UI", 8.5F);
            caption_theoryInput.ForeColor = Color.FromArgb(71, 85, 105);
            caption_theoryInput.TextAlign = ContentAlignment.MiddleLeft;
            caption_sideInput.Text = "造波段";
            caption_sideInput.Dock = DockStyle.Fill;
            caption_sideInput.Font = new Font("Microsoft YaHei UI", 8.5F);
            caption_sideInput.ForeColor = Color.FromArgb(71, 85, 105);
            caption_sideInput.TextAlign = ContentAlignment.MiddleLeft;
            caption_modeInput.Text = "造波模式";
            caption_modeInput.Dock = DockStyle.Fill;
            caption_modeInput.Font = new Font("Microsoft YaHei UI", 8.5F);
            caption_modeInput.ForeColor = Color.FromArgb(71, 85, 105);
            caption_modeInput.TextAlign = ContentAlignment.MiddleLeft;
            depthInput.Dock = DockStyle.Fill;
            depthInput.Margin = new Padding(3, 5, 3, 5);
            depthInput.Font = new Font("Microsoft YaHei UI", 9F);
            depthInput.BackColor = Color.White;
            depthInput.ForeColor = Color.FromArgb(15, 23, 42);
            depthInput.BorderStyle = BorderStyle.FixedSingle;
            depthInput.Maximum = 100M;
            depthInput.Minimum = 0.001M;
            depthInput.DecimalPlaces = 3;
            depthInput.Increment = 0.01M;
            depthInput.Value = 0.6M;
            stepInput.Dock = DockStyle.Fill;
            stepInput.Margin = new Padding(3, 5, 3, 5);
            stepInput.Font = new Font("Microsoft YaHei UI", 9F);
            stepInput.BackColor = Color.White;
            stepInput.ForeColor = Color.FromArgb(15, 23, 42);
            stepInput.BorderStyle = BorderStyle.FixedSingle;
            stepInput.Maximum = 1M;
            stepInput.Minimum = 0.002M;
            stepInput.DecimalPlaces = 3;
            stepInput.Increment = 0.01M;
            stepInput.Value = 0.02M;
            countInput.Dock = DockStyle.Fill;
            countInput.Margin = new Padding(3, 5, 3, 5);
            countInput.Font = new Font("Microsoft YaHei UI", 9F);
            countInput.BackColor = Color.White;
            countInput.ForeColor = Color.FromArgb(15, 23, 42);
            countInput.BorderStyle = BorderStyle.FixedSingle;
            countInput.Maximum = 131072M;
            countInput.Minimum = 64M;
            countInput.DecimalPlaces = 0;
            countInput.Increment = 1M;
            countInput.Value = 8192M;
            seedInput.Dock = DockStyle.Fill;
            seedInput.Margin = new Padding(3, 5, 3, 5);
            seedInput.Font = new Font("Microsoft YaHei UI", 9F);
            seedInput.BackColor = Color.White;
            seedInput.ForeColor = Color.FromArgb(15, 23, 42);
            seedInput.BorderStyle = BorderStyle.FixedSingle;
            seedInput.Maximum = 2147483647M;
            seedInput.Minimum = 0M;
            seedInput.DecimalPlaces = 0;
            seedInput.Increment = 1M;
            seedInput.Value = 30M;
            frequencyInput.Dock = DockStyle.Fill;
            frequencyInput.Margin = new Padding(3, 5, 3, 5);
            frequencyInput.Font = new Font("Microsoft YaHei UI", 9F);
            frequencyInput.BackColor = Color.White;
            frequencyInput.ForeColor = Color.FromArgb(15, 23, 42);
            frequencyInput.BorderStyle = BorderStyle.FixedSingle;
            frequencyInput.Maximum = 100M;
            frequencyInput.Minimum = 0.001M;
            frequencyInput.DecimalPlaces = 3;
            frequencyInput.Increment = 0.01M;
            frequencyInput.Value = 0.514M;
            periodInput.Dock = DockStyle.Fill;
            periodInput.Margin = new Padding(3, 5, 3, 5);
            periodInput.Font = new Font("Microsoft YaHei UI", 9F);
            periodInput.BackColor = Color.White;
            periodInput.ForeColor = Color.FromArgb(15, 23, 42);
            periodInput.BorderStyle = BorderStyle.FixedSingle;
            periodInput.Maximum = 100M;
            periodInput.Minimum = 0.001M;
            periodInput.DecimalPlaces = 3;
            periodInput.Increment = 0.01M;
            periodInput.Value = 4M;
            angleInput.Dock = DockStyle.Fill;
            angleInput.Margin = new Padding(3, 5, 3, 5);
            angleInput.Font = new Font("Microsoft YaHei UI", 9F);
            angleInput.BackColor = Color.White;
            angleInput.ForeColor = Color.FromArgb(15, 23, 42);
            angleInput.BorderStyle = BorderStyle.FixedSingle;
            angleInput.Maximum = 180M;
            angleInput.Minimum = 0M;
            angleInput.DecimalPlaces = 3;
            angleInput.Increment = 0.01M;
            angleInput.Value = 0.6M;
            theoryInput.Dock = DockStyle.Fill;
            theoryInput.Margin = new Padding(3, 5, 3, 5);
            theoryInput.Font = new Font("Microsoft YaHei UI", 9F);
            theoryInput.BackColor = Color.White;
            theoryInput.ForeColor = Color.FromArgb(15, 23, 42);
            theoryInput.FlatStyle = FlatStyle.Flat;
            theoryInput.DropDownStyle = ComboBoxStyle.DropDownList;
            theoryInput.Items.AddRange(new object[] { "线性", "非线性" });
            theoryInput.SelectedIndex = 0;
            sideInput.Dock = DockStyle.Fill;
            sideInput.Margin = new Padding(3, 5, 3, 5);
            sideInput.Font = new Font("Microsoft YaHei UI", 9F);
            sideInput.BackColor = Color.White;
            sideInput.ForeColor = Color.FromArgb(15, 23, 42);
            sideInput.FlatStyle = FlatStyle.Flat;
            sideInput.DropDownStyle = ComboBoxStyle.DropDownList;
            sideInput.Items.AddRange(new object[] { "X轴+Y轴", "X轴", "Y轴" });
            sideInput.SelectedIndex = 0;
            modeInput.Dock = DockStyle.Fill;
            modeInput.Margin = new Padding(3, 5, 3, 5);
            modeInput.Font = new Font("Microsoft YaHei UI", 9F);
            modeInput.BackColor = Color.White;
            modeInput.ForeColor = Color.FromArgb(15, 23, 42);
            modeInput.FlatStyle = FlatStyle.Flat;
            modeInput.DropDownStyle = ComboBoxStyle.DropDownList;
            modeInput.Items.AddRange(new object[] { "单向", "多向" });
            modeInput.SelectedIndex = 0;
            spectrumPath.Dock = DockStyle.Fill;
            spectrumPath.Margin = new Padding(3, 5, 3, 5);
            spectrumPath.ReadOnly = true;
            spectrumPath.BorderStyle = BorderStyle.FixedSingle;
            spectrumPath.BackColor = Color.White;
            spectrumPath.ForeColor = Color.FromArgb(15, 23, 42);
            spectrumPath.Font = new Font("Microsoft YaHei UI", 9F);
            outputPath.Dock = DockStyle.Fill;
            outputPath.Margin = new Padding(3, 5, 3, 5);
            outputPath.ReadOnly = true;
            outputPath.BorderStyle = BorderStyle.FixedSingle;
            outputPath.BackColor = Color.White;
            outputPath.ForeColor = Color.FromArgb(15, 23, 42);
            outputPath.Font = new Font("Microsoft YaHei UI", 9F);
            absorbInput.Text = "吸收式 (0.002s)";
            absorbInput.Dock = DockStyle.Fill;
            absorbInput.Font = new Font("Microsoft YaHei UI", 9F);
            absorbInput.ForeColor = Color.FromArgb(15, 23, 42);
            absorbInput.Margin = new Padding(3, 5, 3, 5);
            spectrumBrowse.Text = "浏览";
            spectrumBrowse.FlatStyle = FlatStyle.Flat;
            spectrumBrowse.Cursor = Cursors.Hand;
            spectrumBrowse.UseVisualStyleBackColor = false;
            spectrumBrowse.Dock = DockStyle.Fill;
            spectrumBrowse.Margin = new Padding(3, 4, 3, 4);
            spectrumBrowse.Font = new Font("Microsoft YaHei UI", 9F);
            spectrumBrowse.BackColor = Color.FromArgb(248, 250, 252);
            spectrumBrowse.ForeColor = Color.FromArgb(15, 23, 42);
            spectrumBrowse.FlatAppearance.BorderSize = 1;
            spectrumBrowse.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            spectrumBrowse.FlatAppearance.MouseOverBackColor = Color.FromArgb(226, 232, 240);
            outputBrowse.Text = "浏览";
            outputBrowse.FlatStyle = FlatStyle.Flat;
            outputBrowse.Cursor = Cursors.Hand;
            outputBrowse.UseVisualStyleBackColor = false;
            outputBrowse.Dock = DockStyle.Fill;
            outputBrowse.Margin = new Padding(3, 4, 3, 4);
            outputBrowse.Font = new Font("Microsoft YaHei UI", 9F);
            outputBrowse.BackColor = Color.FromArgb(248, 250, 252);
            outputBrowse.ForeColor = Color.FromArgb(15, 23, 42);
            outputBrowse.FlatAppearance.BorderSize = 1;
            outputBrowse.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            outputBrowse.FlatAppearance.MouseOverBackColor = Color.FromArgb(226, 232, 240);
            runButton.Text = "计算并保存";
            runButton.FlatStyle = FlatStyle.Flat;
            runButton.Cursor = Cursors.Hand;
            runButton.UseVisualStyleBackColor = false;
            runButton.Size = new Size(160, 34);
            runButton.Font = new Font("Microsoft YaHei UI", 9F, FontStyle.Bold);
            runButton.BackColor = Color.FromArgb(29, 78, 216);
            runButton.ForeColor = Color.White;
            runButton.FlatAppearance.BorderSize = 0;
            runButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            runButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(30, 64, 175);
            previewButton.Text = "查看输入谱";
            previewButton.FlatStyle = FlatStyle.Flat;
            previewButton.Cursor = Cursors.Hand;
            previewButton.UseVisualStyleBackColor = false;
            previewButton.Size = new Size(160, 34);
            previewButton.Font = new Font("Microsoft YaHei UI", 9F);
            previewButton.BackColor = Color.FromArgb(248, 250, 252);
            previewButton.ForeColor = Color.FromArgb(15, 23, 42);
            previewButton.FlatAppearance.BorderSize = 1;
            previewButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            previewButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(226, 232, 240);
            status.Dock = DockStyle.Fill;
            status.Font = new Font("Microsoft YaHei UI", 8.5F);
            status.ForeColor = Color.FromArgb(71, 85, 105);
            status.AutoEllipsis = true;
            status.TextAlign = ContentAlignment.MiddleLeft;
            status.Text = "请选择输入波谱和 CSV 保存路径";
            plot.Dock = DockStyle.Fill;
            plot.MinimumSize = new Size(300, 180);
            plot.Font = new Font("Microsoft YaHei UI", 9F);
            plot.BackColor = Color.White;
            plot.ForeColor = Color.FromArgb(29, 78, 216);
            plot.FirstCaption = "输入谱";
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            AutoScroll = true;
            AutoScrollMinSize = new Size(946, 476);
            BackColor = Color.FromArgb(241, 245, 249);
            ForeColor = Color.FromArgb(15, 23, 42);
            Font = new Font("Microsoft YaHei UI", 9F);
            Name = "CustomSpectrumPage";
            Size = new Size(1104, 606);
            Controls.Add(pagePanel);
            ((System.ComponentModel.ISupportInitialize)depthInput).EndInit();
            ((System.ComponentModel.ISupportInitialize)stepInput).EndInit();
            ((System.ComponentModel.ISupportInitialize)countInput).EndInit();
            ((System.ComponentModel.ISupportInitialize)seedInput).EndInit();
            ((System.ComponentModel.ISupportInitialize)frequencyInput).EndInit();
            ((System.ComponentModel.ISupportInitialize)periodInput).EndInit();
            ((System.ComponentModel.ISupportInitialize)angleInput).EndInit();
            previewGroup.ResumeLayout(false);
            options.ResumeLayout(false);
            options.PerformLayout();
            parameterGroup.ResumeLayout(false);
            parameterGroup.PerformLayout();
            root.ResumeLayout(false);
            pagePanel.ResumeLayout(false);
            ResumeLayout(false);
        }
    }
}
