namespace Page_switching.panel;

partial class CustomSpectrumPage
{
    private TableLayoutPanel root = null!;
    private Label title = null!;
    private FlowLayoutPanel options = null!;
    private TableLayoutPanel body = null!;
    private Label status = null!;
    private TextBox spectrumPath = null!;
    private Button spectrumBrowse = null!;
    private TextBox outputPath = null!;
    private Button outputBrowse = null!;
    private NumericUpDown depthInput = null!;
    private NumericUpDown stepInput = null!;
    private NumericUpDown countInput = null!;
    private NumericUpDown seedInput = null!;
    private NumericUpDown frequencyInput = null!;
    private NumericUpDown periodInput = null!;
    private NumericUpDown angleInput = null!;
    private ComboBox theoryInput = null!;
    private ComboBox sideInput = null!;
    private ComboBox modeInput = null!;
    private CheckBox absorbInput = null!;
    private Button runButton = null!;
    private Button previewButton = null!;
    private Label caption_spectrumPath = null!;
    private Label caption_outputPath = null!;
    private Label caption_depthInput = null!;
    private Label caption_stepInput = null!;
    private Label caption_countInput = null!;
    private Label caption_seedInput = null!;
    private Label caption_frequencyInput = null!;
    private Label caption_periodInput = null!;
    private Label caption_angleInput = null!;
    private Label caption_theoryInput = null!;
    private Label caption_sideInput = null!;
    private Label caption_modeInput = null!;
    private ComparisonPlotControl plot = null!;

    private void InitializeComponent()
    {
        root = new TableLayoutPanel();
        title = new Label();
        options = new FlowLayoutPanel();
        body = new TableLayoutPanel();
        status = new Label();
        spectrumPath = new TextBox();
        spectrumBrowse = new Button();
        outputPath = new TextBox();
        outputBrowse = new Button();
        depthInput = new NumericUpDown();
        stepInput = new NumericUpDown();
        countInput = new NumericUpDown();
        seedInput = new NumericUpDown();
        frequencyInput = new NumericUpDown();
        periodInput = new NumericUpDown();
        angleInput = new NumericUpDown();
        theoryInput = new ComboBox();
        sideInput = new ComboBox();
        modeInput = new ComboBox();
        absorbInput = new CheckBox();
        runButton = new Button();
        previewButton = new Button();
        caption_spectrumPath = new Label();
        caption_outputPath = new Label();
        caption_depthInput = new Label();
        caption_stepInput = new Label();
        caption_countInput = new Label();
        caption_seedInput = new Label();
        caption_frequencyInput = new Label();
        caption_periodInput = new Label();
        caption_angleInput = new Label();
        caption_theoryInput = new Label();
        caption_sideInput = new Label();
        caption_modeInput = new Label();
        plot = new ComparisonPlotControl();
        SuspendLayout();
        root.SuspendLayout();
        options.SuspendLayout();
        body.SuspendLayout();
        root.Name = "root";
        title.Name = "title";
        options.Name = "options";
        body.Name = "body";
        status.Name = "status";
        spectrumPath.Name = "spectrumPath";
        spectrumBrowse.Name = "spectrumBrowse";
        outputPath.Name = "outputPath";
        outputBrowse.Name = "outputBrowse";
        depthInput.Name = "depthInput";
        stepInput.Name = "stepInput";
        countInput.Name = "countInput";
        seedInput.Name = "seedInput";
        frequencyInput.Name = "frequencyInput";
        periodInput.Name = "periodInput";
        angleInput.Name = "angleInput";
        theoryInput.Name = "theoryInput";
        sideInput.Name = "sideInput";
        modeInput.Name = "modeInput";
        absorbInput.Name = "absorbInput";
        runButton.Name = "runButton";
        previewButton.Name = "previewButton";
        caption_spectrumPath.Name = "caption_spectrumPath";
        caption_outputPath.Name = "caption_outputPath";
        caption_depthInput.Name = "caption_depthInput";
        caption_stepInput.Name = "caption_stepInput";
        caption_countInput.Name = "caption_countInput";
        caption_seedInput.Name = "caption_seedInput";
        caption_frequencyInput.Name = "caption_frequencyInput";
        caption_periodInput.Name = "caption_periodInput";
        caption_angleInput.Name = "caption_angleInput";
        caption_theoryInput.Name = "caption_theoryInput";
        caption_sideInput.Name = "caption_sideInput";
        caption_modeInput.Name = "caption_modeInput";
        plot.Name = "plot";
        root.Dock = DockStyle.Fill;
        root.Padding = new Padding(16);
        root.ColumnCount = 1;
        root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        root.RowCount = 4;
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 220F));
        root.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 58F));
        root.BackColor = Color.FromArgb(241, 245, 249);
        root.Controls.Add(title, 0, 0);
        root.Controls.Add(options, 0, 1);
        root.Controls.Add(body, 0, 2);
        root.Controls.Add(status, 0, 3);
        title.Text = "自定义谱生成造波信号";
        title.Font = new Font("Microsoft YaHei UI", 16F, FontStyle.Bold);
        title.Dock = DockStyle.Fill;
        options.Dock = DockStyle.Fill;
        options.BackColor = Color.White;
        options.Padding = new Padding(8);
        options.AutoScroll = true;
        options.WrapContents = true;
        caption_spectrumPath.Text = "输入谱(.dat)";
        caption_spectrumPath.AutoSize = true;
        caption_spectrumPath.Margin = new Padding(6, 9, 3, 3);
        options.Controls.Add(caption_spectrumPath);
        spectrumPath.Margin = new Padding(3, 3, 8, 8);
        spectrumPath.Width = 410;
        spectrumPath.Text = "";
        spectrumPath.ReadOnly = true;
        spectrumPath.BackColor = Color.White;
        spectrumPath.BorderStyle = BorderStyle.FixedSingle;
        options.Controls.Add(spectrumPath);
        options.SetFlowBreak(spectrumPath, false);
        spectrumBrowse.Margin = new Padding(3, 3, 8, 8);
        spectrumBrowse.Text = "选择波谱";
        spectrumBrowse.Size = new Size(125, 32);
        spectrumBrowse.FlatStyle = FlatStyle.Flat;
        spectrumBrowse.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
        spectrumBrowse.BackColor = Color.FromArgb(248, 250, 252);
        options.Controls.Add(spectrumBrowse);
        options.SetFlowBreak(spectrumBrowse, true);
        caption_outputPath.Text = "造波板信号";
        caption_outputPath.AutoSize = true;
        caption_outputPath.Margin = new Padding(6, 9, 3, 3);
        options.Controls.Add(caption_outputPath);
        outputPath.Margin = new Padding(3, 3, 8, 8);
        outputPath.Width = 410;
        outputPath.Text = "";
        outputPath.ReadOnly = true;
        outputPath.BackColor = Color.White;
        outputPath.BorderStyle = BorderStyle.FixedSingle;
        options.Controls.Add(outputPath);
        options.SetFlowBreak(outputPath, false);
        outputBrowse.Margin = new Padding(3, 3, 8, 8);
        outputBrowse.Text = "保存路径";
        outputBrowse.Size = new Size(125, 32);
        outputBrowse.FlatStyle = FlatStyle.Flat;
        outputBrowse.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
        outputBrowse.BackColor = Color.FromArgb(248, 250, 252);
        options.Controls.Add(outputBrowse);
        options.SetFlowBreak(outputBrowse, true);
        caption_depthInput.Text = "水深(m)";
        caption_depthInput.AutoSize = true;
        caption_depthInput.Margin = new Padding(6, 9, 3, 3);
        options.Controls.Add(caption_depthInput);
        depthInput.Margin = new Padding(3, 3, 8, 8);
        depthInput.Width = 78;
        depthInput.Maximum = 100M;
        depthInput.Minimum = 0.001M;
        depthInput.DecimalPlaces = 3;
        depthInput.Increment = 0.01M;
        depthInput.Value = 0.6M;
        options.Controls.Add(depthInput);
        caption_stepInput.Text = "步长(s)";
        caption_stepInput.AutoSize = true;
        caption_stepInput.Margin = new Padding(6, 9, 3, 3);
        options.Controls.Add(caption_stepInput);
        stepInput.Margin = new Padding(3, 3, 8, 8);
        stepInput.Width = 78;
        stepInput.Maximum = 1M;
        stepInput.Minimum = 0.002M;
        stepInput.DecimalPlaces = 3;
        stepInput.Increment = 0.01M;
        stepInput.Value = 0.02M;
        options.Controls.Add(stepInput);
        caption_countInput.Text = "点数";
        caption_countInput.AutoSize = true;
        caption_countInput.Margin = new Padding(6, 9, 3, 3);
        options.Controls.Add(caption_countInput);
        countInput.Margin = new Padding(3, 3, 8, 8);
        countInput.Width = 78;
        countInput.Maximum = 131072M;
        countInput.Minimum = 64M;
        countInput.DecimalPlaces = 0;
        countInput.Increment = 1M;
        countInput.Value = 8192M;
        options.Controls.Add(countInput);
        caption_seedInput.Text = "种子";
        caption_seedInput.AutoSize = true;
        caption_seedInput.Margin = new Padding(6, 9, 3, 3);
        options.Controls.Add(caption_seedInput);
        seedInput.Margin = new Padding(3, 3, 8, 8);
        seedInput.Width = 78;
        seedInput.Maximum = 2147483647M;
        seedInput.Minimum = 0M;
        seedInput.DecimalPlaces = 0;
        seedInput.Increment = 1M;
        seedInput.Value = 30M;
        options.Controls.Add(seedInput);
        caption_frequencyInput.Text = "特征频率(Hz)";
        caption_frequencyInput.AutoSize = true;
        caption_frequencyInput.Margin = new Padding(6, 9, 3, 3);
        options.Controls.Add(caption_frequencyInput);
        frequencyInput.Margin = new Padding(3, 3, 8, 8);
        frequencyInput.Width = 78;
        frequencyInput.Maximum = 100M;
        frequencyInput.Minimum = 0.001M;
        frequencyInput.DecimalPlaces = 3;
        frequencyInput.Increment = 0.01M;
        frequencyInput.Value = 0.514M;
        options.Controls.Add(frequencyInput);
        caption_periodInput.Text = "特征周期(s)";
        caption_periodInput.AutoSize = true;
        caption_periodInput.Margin = new Padding(6, 9, 3, 3);
        options.Controls.Add(caption_periodInput);
        periodInput.Margin = new Padding(3, 3, 8, 8);
        periodInput.Width = 78;
        periodInput.Maximum = 100M;
        periodInput.Minimum = 0.001M;
        periodInput.DecimalPlaces = 3;
        periodInput.Increment = 0.01M;
        periodInput.Value = 4M;
        options.Controls.Add(periodInput);
        options.SetFlowBreak(periodInput, true);
        caption_angleInput.Text = "波向偏角";
        caption_angleInput.AutoSize = true;
        caption_angleInput.Margin = new Padding(6, 9, 3, 3);
        options.Controls.Add(caption_angleInput);
        angleInput.Margin = new Padding(3, 3, 8, 8);
        angleInput.Width = 78;
        angleInput.Maximum = 180M;
        angleInput.Minimum = 0M;
        angleInput.DecimalPlaces = 3;
        angleInput.Increment = 0.01M;
        angleInput.Value = 0.6M;
        options.Controls.Add(angleInput);
        caption_theoryInput.Text = "理论";
        caption_theoryInput.AutoSize = true;
        caption_theoryInput.Margin = new Padding(6, 9, 3, 3);
        options.Controls.Add(caption_theoryInput);
        theoryInput.Margin = new Padding(3, 3, 8, 8);
        theoryInput.DropDownStyle = ComboBoxStyle.DropDownList;
        theoryInput.Width = 135;
        theoryInput.Items.AddRange(new object[] { "线性", "非线性" });
        theoryInput.SelectedIndex = 0;
        options.Controls.Add(theoryInput);
        caption_sideInput.Text = "造波段";
        caption_sideInput.AutoSize = true;
        caption_sideInput.Margin = new Padding(6, 9, 3, 3);
        options.Controls.Add(caption_sideInput);
        sideInput.Margin = new Padding(3, 3, 8, 8);
        sideInput.DropDownStyle = ComboBoxStyle.DropDownList;
        sideInput.Width = 135;
        sideInput.Items.AddRange(new object[] { "X轴+Y轴", "X轴", "Y轴" });
        sideInput.SelectedIndex = 0;
        options.Controls.Add(sideInput);
        caption_modeInput.Text = "模式";
        caption_modeInput.AutoSize = true;
        caption_modeInput.Margin = new Padding(6, 9, 3, 3);
        options.Controls.Add(caption_modeInput);
        modeInput.Margin = new Padding(3, 3, 8, 8);
        modeInput.DropDownStyle = ComboBoxStyle.DropDownList;
        modeInput.Width = 135;
        modeInput.Items.AddRange(new object[] { "单向", "多向" });
        modeInput.SelectedIndex = 0;
        options.Controls.Add(modeInput);
        absorbInput.Margin = new Padding(3, 3, 8, 8);
        absorbInput.Text = "吸收式(0.002s)";
        absorbInput.AutoSize = true;
        absorbInput.Margin = new Padding(8, 8, 8, 8);
        options.Controls.Add(absorbInput);
        runButton.Margin = new Padding(3, 3, 8, 8);
        runButton.Text = "计算并保存";
        runButton.Size = new Size(125, 32);
        runButton.FlatStyle = FlatStyle.Flat;
        runButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
        runButton.BackColor = Color.FromArgb(248, 250, 252);
        runButton.BackColor = Color.FromArgb(29, 78, 216);
        runButton.ForeColor = Color.White;
        options.Controls.Add(runButton);
        previewButton.Margin = new Padding(3, 3, 8, 8);
        previewButton.Text = "查看输入谱";
        previewButton.Size = new Size(125, 32);
        previewButton.FlatStyle = FlatStyle.Flat;
        previewButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
        previewButton.BackColor = Color.FromArgb(248, 250, 252);
        options.Controls.Add(previewButton);
        body.Dock = DockStyle.Fill;
        body.ColumnCount = 1;
        body.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        body.RowCount = 1;
        body.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        plot.Dock = DockStyle.Fill;
        plot.MinimumSize = new Size(300, 180);
        body.Controls.Add(plot, 0, 0);
        status.Text = "调用旧WP-7.exe；输入谱至少包含频率及谱密度列。生成的是旧格式造波板位移。";
        status.Dock = DockStyle.Fill;
        status.AutoEllipsis = true;
        status.ForeColor = Color.FromArgb(71, 85, 105);
        Font = new Font("Microsoft YaHei UI", 9F);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        AutoScroll = true;
        AutoScrollMinSize = new Size(1000, 580);
        Size = new Size(1104, 606);
        Controls.Add(root);
        body.ResumeLayout(false);
        options.ResumeLayout(false);
        options.PerformLayout();
        root.ResumeLayout(false);
        ResumeLayout(false);
    }
}
