namespace Page_switching.panel;

partial class Data
{
    private void InitializeComponent()
    {
        root = new TableLayoutPanel();
        title = new Label();
        filters = new FlowLayoutPanel();
        fromCaption = new Label();
        fromDate = new DateTimePicker();
        toCaption = new Label();
        toDate = new DateTimePicker();
        channelCaption = new Label();
        channelPicker = new ComboBox();
        refreshButton = new Button();
        importButton = new Button();
        exportButton = new Button();
        syncButton = new Button();
        legacyExportButton = new Button();
        analyzeButton = new Button();
        sessionGrid = new DataGridView();
        sessionIdColumn = new DataGridViewTextBoxColumn();
        startedColumn = new DataGridViewTextBoxColumn();
        channelsColumn = new DataGridViewTextBoxColumn();
        countColumn = new DataGridViewTextBoxColumn();
        syncColumn = new DataGridViewTextBoxColumn();
        content = new TableLayoutPanel();
        sampleGrid = new DataGridView();
        timeColumn = new DataGridViewTextBoxColumn();
        sampleChannelColumn = new DataGridViewTextBoxColumn();
        rawColumn = new DataGridViewTextBoxColumn();
        levelColumn = new DataGridViewTextBoxColumn();
        preview = new WaveformPreviewControl();
        status = new Label();
        ((System.ComponentModel.ISupportInitialize)sessionGrid).BeginInit();
        ((System.ComponentModel.ISupportInitialize)sampleGrid).BeginInit();
        SuspendLayout();
        legacyExportButton.Name = "legacyExportButton";
        legacyExportButton.Text = "导出旧TXT";
        legacyExportButton.Size = new Size(112, 34);
        legacyExportButton.FlatStyle = FlatStyle.Flat;
        legacyExportButton.BackColor = Color.FromArgb(248, 250, 252);
        legacyExportButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
        analyzeButton.Name = "analyzeButton";
        analyzeButton.Text = "分析所选记录";
        analyzeButton.Size = new Size(125, 34);
        analyzeButton.FlatStyle = FlatStyle.Flat;
        analyzeButton.BackColor = Color.FromArgb(29, 78, 216);
        analyzeButton.ForeColor = Color.White;

        root.BackColor = Color.FromArgb(241, 245, 249);
        root.ColumnCount = 1;
        root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        root.Dock = DockStyle.Fill;
        root.Padding = new Padding(16);
        root.RowCount = 5;

        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 48F));
        root.RowStyles.Add(new RowStyle(SizeType.AutoSize));
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 180F));
        root.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        root.Name = "root";
        root.AutoScroll = false;

        title.Dock = DockStyle.Fill;
        title.Font = new Font("Microsoft YaHei UI", 16F, FontStyle.Bold);
        title.ForeColor = Color.FromArgb(15, 23, 42);
        title.Name = "title";
        title.Text = "采集数据管理";
        root.Controls.Add(title, 0, 0);

        filters.BackColor = Color.White;
        filters.BorderStyle = BorderStyle.None;
        filters.Dock = DockStyle.Fill;
        filters.Padding = new Padding(12, 10, 12, 10);
        filters.Name = "filters";
        filters.MinimumSize = new Size(0, 58);
        filters.AutoSizeMode = AutoSizeMode.GrowAndShrink;
        filters.AutoSize = true;
        filters.AutoScroll = true;
        filters.WrapContents = true;
        root.Controls.Add(filters, 0, 1);
        fromCaption.AutoSize = true;
        fromCaption.Margin = new Padding(0, 11, 4, 0);
        fromCaption.Name = "fromCaption";
        fromCaption.Text = "开始";
        filters.Controls.Add(fromCaption);
        fromDate.Format = DateTimePickerFormat.Custom;
        fromDate.CalendarForeColor = Color.FromArgb(15, 23, 42);
        fromDate.CalendarMonthBackground = Color.White;
        fromDate.Name = "fromDate";
        fromDate.CustomFormat = "yyyy-MM-dd";
        fromDate.Size = new Size(115, 29);
        filters.Controls.Add(fromDate);
        toCaption.AutoSize = true;
        toCaption.Margin = new Padding(10, 11, 4, 0);
        toCaption.Name = "toCaption";
        toCaption.Text = "结束";
        filters.Controls.Add(toCaption);
        toDate.Format = DateTimePickerFormat.Custom;
        toDate.CalendarForeColor = Color.FromArgb(15, 23, 42);
        toDate.CalendarMonthBackground = Color.White;
        toDate.Name = "toDate";
        toDate.CustomFormat = "yyyy-MM-dd";
        toDate.Size = new Size(115, 29);
        filters.Controls.Add(toDate);
        channelCaption.AutoSize = true;
        channelCaption.Margin = new Padding(10, 11, 4, 0);
        channelCaption.Name = "channelCaption";
        channelCaption.Text = "通道";
        filters.Controls.Add(channelCaption);
        channelPicker.DropDownStyle = ComboBoxStyle.DropDownList;
        channelPicker.BackColor = Color.White;
        channelPicker.ForeColor = Color.FromArgb(15, 23, 42);
        channelPicker.Name = "channelPicker";
        channelPicker.FlatStyle = FlatStyle.Flat;
        channelPicker.Size = new Size(88, 29);
        filters.Controls.Add(channelPicker);
        refreshButton.BackColor = Color.FromArgb(29, 78, 216);
        refreshButton.FlatAppearance.BorderSize = 0;
        refreshButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(30, 64, 175);
        refreshButton.FlatStyle = FlatStyle.Flat;
        refreshButton.ForeColor = Color.White;
        refreshButton.Name = "refreshButton";
        refreshButton.Cursor = Cursors.Hand;
        refreshButton.Size = new Size(82, 34);
        refreshButton.Text = "查询";
        refreshButton.UseVisualStyleBackColor = false;
        filters.Controls.Add(refreshButton);
        importButton.BackColor = Color.FromArgb(248, 250, 252);
        importButton.FlatAppearance.BorderSize = 1;
        importButton.FlatStyle = FlatStyle.Flat;
        importButton.ForeColor = Color.FromArgb(15, 23, 42);
        importButton.Name = "importButton";
        importButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(226, 232, 240);
        importButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
        importButton.Cursor = Cursors.Hand;
        importButton.Size = new Size(110, 34);
        importButton.Text = "导入旧数据";
        importButton.UseVisualStyleBackColor = false;
        filters.Controls.Add(importButton);
        exportButton.BackColor = Color.FromArgb(248, 250, 252);
        exportButton.FlatAppearance.BorderSize = 1;
        exportButton.FlatStyle = FlatStyle.Flat;
        exportButton.ForeColor = Color.FromArgb(15, 23, 42);
        exportButton.Name = "exportButton";
        exportButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(226, 232, 240);
        exportButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
        exportButton.Cursor = Cursors.Hand;
        exportButton.Size = new Size(96, 34);
        exportButton.Text = "导出 CSV";
        exportButton.UseVisualStyleBackColor = false;
        filters.Controls.Add(exportButton);
        syncButton.BackColor = Color.FromArgb(248, 250, 252);
        syncButton.FlatAppearance.BorderSize = 1;
        syncButton.FlatStyle = FlatStyle.Flat;
        syncButton.ForeColor = Color.FromArgb(15, 23, 42);
        syncButton.Name = "syncButton";
        syncButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(226, 232, 240);
        syncButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
        syncButton.Cursor = Cursors.Hand;
        syncButton.Size = new Size(110, 34);
        syncButton.Text = "同步数据库";
        syncButton.UseVisualStyleBackColor = false;
        filters.Controls.Add(syncButton);
        filters.Controls.Add(legacyExportButton);
        filters.Controls.Add(analyzeButton);

        sessionGrid.AllowUserToAddRows = false;
        sessionGrid.AllowUserToDeleteRows = false;
        sessionGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        sessionGrid.BackgroundColor = Color.White;
        sessionGrid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(248, 250, 252);
        sessionGrid.ColumnHeadersDefaultCellStyle.ForeColor = Color.FromArgb(15, 23, 42);
        sessionGrid.DefaultCellStyle.BackColor = Color.White;
        sessionGrid.DefaultCellStyle.ForeColor = Color.FromArgb(15, 23, 42);
        sessionGrid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(219, 234, 254);
        sessionGrid.DefaultCellStyle.SelectionForeColor = Color.FromArgb(15, 23, 42);
        sessionGrid.EnableHeadersVisualStyles = false;
        sessionGrid.GridColor = Color.FromArgb(226, 232, 240);
        sessionGrid.RowHeadersDefaultCellStyle.BackColor = Color.FromArgb(241, 245, 249);
        sessionGrid.RowHeadersDefaultCellStyle.ForeColor = Color.FromArgb(15, 23, 42);
        sessionGrid.RowHeadersDefaultCellStyle.SelectionBackColor = Color.FromArgb(219, 234, 254);
        sessionGrid.RowHeadersDefaultCellStyle.SelectionForeColor = Color.FromArgb(15, 23, 42);
        sessionGrid.Columns.AddRange(sessionIdColumn, startedColumn, channelsColumn, countColumn, syncColumn);
        sessionGrid.Dock = DockStyle.Fill;
        sessionGrid.MultiSelect = false;
        sessionGrid.Name = "sessionGrid";
        sessionGrid.ColumnHeadersDefaultCellStyle.SelectionForeColor = Color.FromArgb(15, 23, 42);
        sessionGrid.ColumnHeadersDefaultCellStyle.SelectionBackColor = Color.FromArgb(248, 250, 252);
        sessionGrid.Margin = new Padding(0, 10, 0, 8);
        sessionGrid.AllowUserToResizeRows = false;
        sessionGrid.RowTemplate.Height = 30;
        sessionGrid.RowHeadersVisible = false;
        sessionGrid.AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(248, 250, 252);
        sessionGrid.DefaultCellStyle.Padding = new Padding(8, 0, 8, 0);
        sessionGrid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        sessionGrid.ColumnHeadersHeight = 36;
        sessionGrid.ColumnHeadersDefaultCellStyle.Font = new Font("Microsoft YaHei UI", 9F, FontStyle.Bold);
        sessionGrid.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
        sessionGrid.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
        sessionGrid.BorderStyle = BorderStyle.None;
        sessionGrid.ReadOnly = true;
        sessionGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        sessionIdColumn.HeaderText = "任务 ID";
        sessionIdColumn.Name = "sessionIdColumn";
        sessionIdColumn.FillWeight = 85F;
        startedColumn.HeaderText = "开始时间";
        startedColumn.Name = "startedColumn";
        startedColumn.FillWeight = 150F;
        channelsColumn.HeaderText = "通道";
        channelsColumn.Name = "channelsColumn";
        channelsColumn.FillWeight = 75F;
        countColumn.HeaderText = "样本数";
        countColumn.Name = "countColumn";
        syncColumn.HeaderText = "数据库";
        syncColumn.Name = "syncColumn";
        root.Controls.Add(sessionGrid, 0, 2);

        content.ColumnCount = 2;
        content.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        content.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        content.Dock = DockStyle.Fill;
        content.Name = "content";
        content.Margin = new Padding(0, 0, 0, 8);
        content.RowCount = 1;
        content.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        root.Controls.Add(content, 0, 3);
        sampleGrid.AllowUserToAddRows = false;
        sampleGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        sampleGrid.BackgroundColor = Color.White;
        sampleGrid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(248, 250, 252);
        sampleGrid.ColumnHeadersDefaultCellStyle.ForeColor = Color.FromArgb(15, 23, 42);
        sampleGrid.DefaultCellStyle.BackColor = Color.White;
        sampleGrid.DefaultCellStyle.ForeColor = Color.FromArgb(15, 23, 42);
        sampleGrid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(219, 234, 254);
        sampleGrid.DefaultCellStyle.SelectionForeColor = Color.FromArgb(15, 23, 42);
        sampleGrid.EnableHeadersVisualStyles = false;
        sampleGrid.GridColor = Color.FromArgb(226, 232, 240);
        sampleGrid.RowHeadersDefaultCellStyle.BackColor = Color.FromArgb(241, 245, 249);
        sampleGrid.RowHeadersDefaultCellStyle.ForeColor = Color.FromArgb(15, 23, 42);
        sampleGrid.RowHeadersDefaultCellStyle.SelectionBackColor = Color.FromArgb(219, 234, 254);
        sampleGrid.RowHeadersDefaultCellStyle.SelectionForeColor = Color.FromArgb(15, 23, 42);
        sampleGrid.Columns.AddRange(timeColumn, sampleChannelColumn, rawColumn, levelColumn);
        sampleGrid.Dock = DockStyle.Fill;
        sampleGrid.Name = "sampleGrid";
        sampleGrid.ColumnHeadersDefaultCellStyle.SelectionForeColor = Color.FromArgb(15, 23, 42);
        sampleGrid.ColumnHeadersDefaultCellStyle.SelectionBackColor = Color.FromArgb(248, 250, 252);
        sampleGrid.Margin = new Padding(0, 0, 8, 0);
        sampleGrid.AllowUserToResizeRows = false;
        sampleGrid.RowTemplate.Height = 30;
        sampleGrid.RowHeadersVisible = false;
        sampleGrid.AlternatingRowsDefaultCellStyle.BackColor = Color.FromArgb(248, 250, 252);
        sampleGrid.DefaultCellStyle.Padding = new Padding(8, 0, 8, 0);
        sampleGrid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.DisableResizing;
        sampleGrid.ColumnHeadersHeight = 36;
        sampleGrid.ColumnHeadersDefaultCellStyle.Font = new Font("Microsoft YaHei UI", 9F, FontStyle.Bold);
        sampleGrid.ColumnHeadersBorderStyle = DataGridViewHeaderBorderStyle.None;
        sampleGrid.CellBorderStyle = DataGridViewCellBorderStyle.SingleHorizontal;
        sampleGrid.BorderStyle = BorderStyle.None;
        sampleGrid.ReadOnly = true;
        sampleGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        timeColumn.HeaderText = "采样时间";
        timeColumn.Name = "timeColumn";
        sampleChannelColumn.HeaderText = "通道";
        sampleChannelColumn.Name = "sampleChannelColumn";
        rawColumn.HeaderText = "原始计数";
        rawColumn.Name = "rawColumn";
        levelColumn.HeaderText = "标定值 (mm)";
        levelColumn.Name = "levelColumn";
        content.Controls.Add(sampleGrid, 0, 0);
        preview.Dock = DockStyle.Fill;
        preview.MinimumSize = new Size(300, 150);
        preview.Name = "preview";
        preview.Margin = new Padding(0);
        preview.UnitText = "mm";
        content.Controls.Add(preview, 1, 0);
        status.BackColor = Color.White;
        status.ForeColor = Color.FromArgb(71, 85, 105);
        status.Dock = DockStyle.Fill;
        status.Name = "status";
        status.AutoEllipsis = true;
        status.Padding = new Padding(10);
        status.Text = "选择采集任务后查看数据。";
        root.Controls.Add(status, 0, 4);

        BackColor = Color.FromArgb(241, 245, 249);
        ForeColor = Color.FromArgb(15, 23, 42);
        Controls.Add(root);
        Font = new Font("Microsoft YaHei UI", 9F);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        AutoScroll = true;
        AutoScrollMinSize = new Size(860, 580);
        Name = "Data";
        Size = new Size(1104, 606);
        ((System.ComponentModel.ISupportInitialize)sessionGrid).EndInit();
        ((System.ComponentModel.ISupportInitialize)sampleGrid).EndInit();
        ResumeLayout(false);
    }

    private TableLayoutPanel root;
    private Label title;
    private FlowLayoutPanel filters;
    private Label fromCaption;
    private DateTimePicker fromDate;
    private Label toCaption;
    private DateTimePicker toDate;
    private Label channelCaption;
    private ComboBox channelPicker;
    private Button refreshButton;
    private Button importButton;
    private Button exportButton;
    private Button syncButton;
    private Button legacyExportButton;
    private Button analyzeButton;
    private DataGridView sessionGrid;
    private DataGridViewTextBoxColumn sessionIdColumn;
    private DataGridViewTextBoxColumn startedColumn;
    private DataGridViewTextBoxColumn channelsColumn;
    private DataGridViewTextBoxColumn countColumn;
    private DataGridViewTextBoxColumn syncColumn;
    private TableLayoutPanel content;
    private DataGridView sampleGrid;
    private DataGridViewTextBoxColumn timeColumn;
    private DataGridViewTextBoxColumn sampleChannelColumn;
    private DataGridViewTextBoxColumn rawColumn;
    private DataGridViewTextBoxColumn levelColumn;
    private WaveformPreviewControl preview;
    private Label status;
}
