namespace Page_switching.panel;

partial class Data
{
    private void InitializeComponent()
    {
        root = new TableLayoutPanel();
        title = new Label();
        filters = new CardFlowPanel();
        fromCaption = new Label();
        fromDate = new DateTimePicker();
        toCaption = new Label();
        toDate = new DateTimePicker();
        channelCaption = new Label();
        channelPicker = new ComboBox();
        refreshButton = new UiButton();
        importButton = new UiButton();
        exportButton = new UiButton();
        syncButton = new UiButton();
        sessionGrid = new UiDataGridView();
        sessionIdColumn = new DataGridViewTextBoxColumn();
        startedColumn = new DataGridViewTextBoxColumn();
        channelsColumn = new DataGridViewTextBoxColumn();
        countColumn = new DataGridViewTextBoxColumn();
        syncColumn = new DataGridViewTextBoxColumn();
        content = new TableLayoutPanel();
        sampleGrid = new UiDataGridView();
        timeColumn = new DataGridViewTextBoxColumn();
        sampleChannelColumn = new DataGridViewTextBoxColumn();
        rawColumn = new DataGridViewTextBoxColumn();
        levelColumn = new DataGridViewTextBoxColumn();
        preview = new WaveformPreviewControl();
        status = new Label();
        ((System.ComponentModel.ISupportInitialize)sessionGrid).BeginInit();
        ((System.ComponentModel.ISupportInitialize)sampleGrid).BeginInit();
        SuspendLayout();

        root.BackColor = Color.FromArgb(241, 245, 249);
        root.ColumnCount = 1;
        root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        root.Dock = DockStyle.Fill;
        root.Padding = new Padding(22, 18, 22, 18);
        root.RowCount = 5;
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 58F));
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 92F));
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 205F));
        root.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 45F));
        root.Name = "root";

        title.Dock = DockStyle.Fill;
        title.Font = new Font("Microsoft YaHei UI", 18F, FontStyle.Bold);
        title.ForeColor = Color.FromArgb(15, 23, 42);
        title.Name = "title";
        title.Text = "采集数据管理";
        root.Controls.Add(title, 0, 0);

        filters.BackColor = Color.White;
        filters.Dock = DockStyle.Fill;
        filters.Padding = new Padding(10);
        filters.Name = "filters";
        filters.AutoScroll = true;
        filters.WrapContents = true;
        root.Controls.Add(filters, 0, 1);
        fromCaption.AutoSize = true;
        fromCaption.Margin = new Padding(0, 11, 4, 0);
        fromCaption.Name = "fromCaption";
        fromCaption.Text = "开始";
        filters.Controls.Add(fromCaption);
        fromDate.Format = DateTimePickerFormat.Short;
        fromDate.CalendarForeColor = Color.FromArgb(15, 23, 42);
        fromDate.CalendarMonthBackground = Color.White;
        fromDate.Name = "fromDate";
        fromDate.Size = new Size(115, 29);
        filters.Controls.Add(fromDate);
        toCaption.AutoSize = true;
        toCaption.Margin = new Padding(10, 11, 4, 0);
        toCaption.Name = "toCaption";
        toCaption.Text = "结束";
        filters.Controls.Add(toCaption);
        toDate.Format = DateTimePickerFormat.Short;
        toDate.CalendarForeColor = Color.FromArgb(15, 23, 42);
        toDate.CalendarMonthBackground = Color.White;
        toDate.Name = "toDate";
        toDate.Size = new Size(115, 29);
        filters.Controls.Add(toDate);
        channelCaption.AutoSize = true;
        channelCaption.Margin = new Padding(10, 11, 4, 0);
        channelCaption.Name = "channelCaption";
        channelCaption.Text = "通道";
        filters.Controls.Add(channelCaption);
        channelPicker.DropDownStyle = ComboBoxStyle.DropDownList;
        channelPicker.BackColor = Color.White;
        channelPicker.ForeColor = Color.FromArgb(15, 23, 42);
        channelPicker.Name = "channelPicker";
        channelPicker.Size = new Size(88, 29);
        filters.Controls.Add(channelPicker);
        refreshButton.BackColor = Color.FromArgb(29, 78, 216);
        refreshButton.FlatAppearance.BorderSize = 0;
        refreshButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(30, 64, 175);
        refreshButton.FlatStyle = FlatStyle.Flat;
        refreshButton.ForeColor = Color.White;
        refreshButton.Name = "refreshButton";
        refreshButton.Size = new Size(82, 32);
        refreshButton.Text = "查询";
        refreshButton.UseVisualStyleBackColor = false;
        filters.Controls.Add(refreshButton);
        importButton.BackColor = Color.FromArgb(226, 232, 240);
        importButton.FlatAppearance.BorderSize = 0;
        importButton.FlatStyle = FlatStyle.Flat;
        importButton.ForeColor = Color.FromArgb(15, 23, 42);
        importButton.Name = "importButton";
        importButton.Size = new Size(110, 32);
        importButton.Text = "导入旧数据";
        importButton.UseVisualStyleBackColor = false;
        filters.Controls.Add(importButton);
        exportButton.BackColor = Color.FromArgb(226, 232, 240);
        exportButton.FlatAppearance.BorderSize = 0;
        exportButton.FlatStyle = FlatStyle.Flat;
        exportButton.ForeColor = Color.FromArgb(15, 23, 42);
        exportButton.Name = "exportButton";
        exportButton.Size = new Size(96, 32);
        exportButton.Text = "导出 CSV";
        exportButton.UseVisualStyleBackColor = false;
        filters.Controls.Add(exportButton);
        syncButton.BackColor = Color.FromArgb(226, 232, 240);
        syncButton.FlatAppearance.BorderSize = 0;
        syncButton.FlatStyle = FlatStyle.Flat;
        syncButton.ForeColor = Color.FromArgb(15, 23, 42);
        syncButton.Name = "syncButton";
        syncButton.Size = new Size(110, 32);
        syncButton.Text = "同步数据库";
        syncButton.UseVisualStyleBackColor = false;
        filters.Controls.Add(syncButton);

        sessionGrid.AllowUserToAddRows = false;
        sessionGrid.AllowUserToDeleteRows = false;
        sessionGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        sessionGrid.BackgroundColor = Color.White;
        sessionGrid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(241, 245, 249);
        sessionGrid.ColumnHeadersDefaultCellStyle.ForeColor = Color.FromArgb(15, 23, 42);
        sessionGrid.DefaultCellStyle.BackColor = Color.White;
        sessionGrid.DefaultCellStyle.ForeColor = Color.FromArgb(15, 23, 42);
        sessionGrid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(219, 234, 254);
        sessionGrid.DefaultCellStyle.SelectionForeColor = Color.FromArgb(15, 23, 42);
        sessionGrid.EnableHeadersVisualStyles = false;
        sessionGrid.GridColor = Color.FromArgb(203, 213, 225);
        sessionGrid.RowHeadersDefaultCellStyle.BackColor = Color.FromArgb(241, 245, 249);
        sessionGrid.RowHeadersDefaultCellStyle.ForeColor = Color.FromArgb(15, 23, 42);
        sessionGrid.RowHeadersDefaultCellStyle.SelectionBackColor = Color.FromArgb(219, 234, 254);
        sessionGrid.RowHeadersDefaultCellStyle.SelectionForeColor = Color.FromArgb(15, 23, 42);
        sessionGrid.Columns.AddRange(sessionIdColumn, startedColumn, channelsColumn, countColumn, syncColumn);
        sessionGrid.Dock = DockStyle.Fill;
        sessionGrid.EmptyText = "暂无采集任务";
        sessionGrid.Margin = new Padding(0, 8, 0, 8);
        sessionGrid.MultiSelect = false;
        sessionGrid.Name = "sessionGrid";
        sessionGrid.ReadOnly = true;
        sessionGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        sessionIdColumn.HeaderText = "任务 ID";
        sessionIdColumn.Name = "sessionIdColumn";
        startedColumn.HeaderText = "开始时间";
        startedColumn.Name = "startedColumn";
        channelsColumn.HeaderText = "通道";
        channelsColumn.Name = "channelsColumn";
        countColumn.HeaderText = "样本数";
        countColumn.Name = "countColumn";
        syncColumn.HeaderText = "数据库";
        syncColumn.Name = "syncColumn";
        root.Controls.Add(sessionGrid, 0, 2);

        content.ColumnCount = 2;
        content.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        content.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        content.Dock = DockStyle.Fill;
        content.Margin = new Padding(0, 0, 0, 8);
        content.Name = "content";
        content.RowCount = 1;
        content.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        root.Controls.Add(content, 0, 3);
        sampleGrid.AllowUserToAddRows = false;
        sampleGrid.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        sampleGrid.BackgroundColor = Color.White;
        sampleGrid.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(241, 245, 249);
        sampleGrid.ColumnHeadersDefaultCellStyle.ForeColor = Color.FromArgb(15, 23, 42);
        sampleGrid.DefaultCellStyle.BackColor = Color.White;
        sampleGrid.DefaultCellStyle.ForeColor = Color.FromArgb(15, 23, 42);
        sampleGrid.DefaultCellStyle.SelectionBackColor = Color.FromArgb(219, 234, 254);
        sampleGrid.DefaultCellStyle.SelectionForeColor = Color.FromArgb(15, 23, 42);
        sampleGrid.EnableHeadersVisualStyles = false;
        sampleGrid.GridColor = Color.FromArgb(203, 213, 225);
        sampleGrid.RowHeadersDefaultCellStyle.BackColor = Color.FromArgb(241, 245, 249);
        sampleGrid.RowHeadersDefaultCellStyle.ForeColor = Color.FromArgb(15, 23, 42);
        sampleGrid.RowHeadersDefaultCellStyle.SelectionBackColor = Color.FromArgb(219, 234, 254);
        sampleGrid.RowHeadersDefaultCellStyle.SelectionForeColor = Color.FromArgb(15, 23, 42);
        sampleGrid.Columns.AddRange(timeColumn, sampleChannelColumn, rawColumn, levelColumn);
        sampleGrid.Dock = DockStyle.Fill;
        sampleGrid.EmptyText = "选择任务后显示采样数据";
        sampleGrid.Margin = new Padding(0, 0, 8, 0);
        sampleGrid.Name = "sampleGrid";
        sampleGrid.ReadOnly = true;
        sampleGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        timeColumn.HeaderText = "采样时间";
        timeColumn.Name = "timeColumn";
        sampleChannelColumn.HeaderText = "通道";
        sampleChannelColumn.Name = "sampleChannelColumn";
        rawColumn.HeaderText = "原始计数";
        rawColumn.Name = "rawColumn";
        levelColumn.HeaderText = "标定值 (mm)";
        levelColumn.Name = "levelColumn";
        content.Controls.Add(sampleGrid, 0, 0);
        preview.Dock = DockStyle.Fill;
        preview.Margin = new Padding(8, 0, 0, 0);
        preview.MinimumSize = new Size(300, 220);
        preview.Name = "preview";
        preview.UnitText = "mm";
        content.Controls.Add(preview, 1, 0);
        status.BackColor = Color.White;
        status.ForeColor = Color.FromArgb(71, 85, 105);
        status.Dock = DockStyle.Fill;
        status.Name = "status";
        status.Padding = new Padding(10);
        status.Text = "选择采集任务后查看数据。";
        root.Controls.Add(status, 0, 4);

        BackColor = Color.FromArgb(241, 245, 249);
        ForeColor = Color.FromArgb(15, 23, 42);
        Controls.Add(root);
        AutoScaleDimensions = new SizeF(9F, 20F);
        AutoScaleMode = AutoScaleMode.Font;
        Name = "Data";
        Size = new Size(1210, 796);
        ((System.ComponentModel.ISupportInitialize)sessionGrid).EndInit();
        ((System.ComponentModel.ISupportInitialize)sampleGrid).EndInit();
        ResumeLayout(false);
    }

    private TableLayoutPanel root;
    private Label title;
    private CardFlowPanel filters;
    private Label fromCaption;
    private DateTimePicker fromDate;
    private Label toCaption;
    private DateTimePicker toDate;
    private Label channelCaption;
    private ComboBox channelPicker;
    private UiButton refreshButton;
    private UiButton importButton;
    private UiButton exportButton;
    private UiButton syncButton;
    private UiDataGridView sessionGrid;
    private DataGridViewTextBoxColumn sessionIdColumn;
    private DataGridViewTextBoxColumn startedColumn;
    private DataGridViewTextBoxColumn channelsColumn;
    private DataGridViewTextBoxColumn countColumn;
    private DataGridViewTextBoxColumn syncColumn;
    private TableLayoutPanel content;
    private UiDataGridView sampleGrid;
    private DataGridViewTextBoxColumn timeColumn;
    private DataGridViewTextBoxColumn sampleChannelColumn;
    private DataGridViewTextBoxColumn rawColumn;
    private DataGridViewTextBoxColumn levelColumn;
    private WaveformPreviewControl preview;
    private Label status;
}
