namespace Page_switching.panel;

partial class LegacyEquipmentPage
{
    private TableLayoutPanel root = null!;
    private Label title = null!;
    private FlowLayoutPanel tools = null!;
    private Button browseButton = null!;
    private Button connectButton = null!;
    private Button saveButton = null!;
    private PropertyGrid properties = null!;
    private TableLayoutPanel body = null!;
    private TableLayoutPanel feedback = null!;
    private FlowLayoutPanel feedbackTools = null!;
    private ComboBox sensorInput = null!;
    private Button readButton = null!;
    private Button fitButton = null!;
    private Button writeButton = null!;
    private DataGridView points = null!;
    private Label status = null!;

    private void InitializeComponent()
    {
        root = new TableLayoutPanel();
        title = new Label();
        tools = new FlowLayoutPanel();
        browseButton = new Button();
        connectButton = new Button();
        saveButton = new Button();
        properties = new PropertyGrid();
        body = new TableLayoutPanel();
        feedback = new TableLayoutPanel();
        feedbackTools = new FlowLayoutPanel();
        sensorInput = new ComboBox();
        readButton = new Button();
        fitButton = new Button();
        writeButton = new Button();
        points = new DataGridView();
        status = new Label();
        SuspendLayout();
        root.Dock = DockStyle.Fill;
        root.Padding = new Padding(16);
        root.ColumnCount = 1;
        root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        root.RowCount = 4;
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 46F));
        root.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 58F));
        root.BackColor = Color.FromArgb(241, 245, 249);
        title.Text = "旧设备配置与反馈传感器标定";
        title.Dock = DockStyle.Fill;
        title.Font = new Font("Microsoft YaHei UI", 16F, FontStyle.Bold);
        tools.Dock = DockStyle.Fill;
        tools.Controls.Add(browseButton);
        tools.Controls.Add(saveButton);
        tools.Controls.Add(connectButton);
        connectButton.Name = "connectButton";
        connectButton.Text = "连接反馈PLC";
        connectButton.Size = new Size(140, 32);
        browseButton.Name = "browseButton";
        browseButton.Text = "选择计算程序目录";
        browseButton.Size = new Size(160, 32);
        saveButton.Name = "saveButton";
        saveButton.Text = "保存设备配置";
        saveButton.Size = new Size(140, 32);
        saveButton.BackColor = Color.FromArgb(29, 78, 216);
        saveButton.ForeColor = Color.White;
        saveButton.FlatStyle = FlatStyle.Flat;
        body.Dock = DockStyle.Fill;
        body.ColumnCount = 2;
        body.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        body.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 50F));
        body.RowCount = 1;
        body.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        properties.Name = "properties";
        properties.Dock = DockStyle.Fill;
        properties.HelpVisible = true;
        properties.ToolbarVisible = false;
        properties.ViewBackColor = Color.White;
        feedback.Dock = DockStyle.Fill;
        feedback.ColumnCount = 1;
        feedback.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        feedback.RowCount = 2;
        feedback.RowStyles.Add(new RowStyle(SizeType.Absolute, 85F));
        feedback.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        feedbackTools.Dock = DockStyle.Fill;
        sensorInput.Name = "sensorInput";
        sensorInput.DropDownStyle = ComboBoxStyle.DropDownList;
        sensorInput.Items.AddRange(new object[] { "反馈传感器A", "反馈传感器B" });
        sensorInput.SelectedIndex = 0;
        sensorInput.Width = 140;
        readButton.Name = "readButton";
        readButton.Text = "读取并添加点";
        readButton.Size = new Size(125, 32);
        fitButton.Name = "fitButton";
        fitButton.Text = "计算并保存";
        fitButton.Size = new Size(125, 32);
        writeButton.Name = "writeButton";
        writeButton.Text = "写入A/B系数到PLC";
        writeButton.Size = new Size(160, 32);
        feedbackTools.Controls.Add(sensorInput);
        feedbackTools.Controls.Add(readButton);
        feedbackTools.Controls.Add(fitButton);
        feedbackTools.Controls.Add(writeButton);
        points.Name = "points";
        points.Dock = DockStyle.Fill;
        points.BackgroundColor = Color.White;
        points.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        points.Columns.Add("raw", "原始反馈计数");
        points.Columns.Add("level", "实测位移(mm)");
        feedback.Controls.Add(feedbackTools, 0, 0);
        feedback.Controls.Add(points, 0, 1);
        body.Controls.Add(properties, 0, 0);
        body.Controls.Add(feedback, 1, 0);
        status.Name = "status";
        status.Text = "反馈A/B通过旧PLC读取，与浪高仪CH1–6标定分开。标定点不足或原始值全部相同不能保存。";
        status.Dock = DockStyle.Fill;
        status.AutoEllipsis = true;
        root.Controls.Add(title, 0, 0);
        root.Controls.Add(tools, 0, 1);
        root.Controls.Add(body, 0, 2);
        root.Controls.Add(status, 0, 3);
        Font = new Font("Microsoft YaHei UI", 9F);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        AutoScroll = true;
        AutoScrollMinSize = new Size(860, 550);
        Size = new Size(1104, 606);
        Controls.Add(root);
        ResumeLayout(false);
    }
}
