namespace Page_switching.panel
{
    partial class SignalCorrectionPage
    {
        private Panel pagePanel;

        private System.ComponentModel.IContainer components = null;
        private TableLayoutPanel root;
        private Label title;
        private FlowLayoutPanel options;
        private TableLayoutPanel body;
        private Label status;
        private TextBox originalPath;
        private Button originalBrowse;
        private TextBox measuredPath;
        private Button measuredBrowse;
        private TextBox outputPath;
        private Button outputBrowse;
        private ComboBox unitInput;
        private NumericUpDown rateInput;
        private NumericUpDown channelInput;
        private NumericUpDown passesInput;
        private NumericUpDown pointsInput;
        private Button runButton;
        private Button previewButton;
        private Label caption_originalPath;
        private Label caption_measuredPath;
        private Label caption_outputPath;
        private Label caption_unitInput;
        private Label caption_rateInput;
        private Label caption_channelInput;
        private Label caption_passesInput;
        private Label caption_pointsInput;
        private ComparisonPlotControl plot;

        protected override void Dispose(bool disposing)
        {
            if (disposing) components?.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            pagePanel = new Panel();
            components = new System.ComponentModel.Container();
            root = new TableLayoutPanel();
            title = new Label();
            options = new FlowLayoutPanel();
            body = new TableLayoutPanel();
            status = new Label();
            originalPath = new TextBox();
            originalBrowse = new Button();
            measuredPath = new TextBox();
            measuredBrowse = new Button();
            outputPath = new TextBox();
            outputBrowse = new Button();
            unitInput = new ComboBox();
            rateInput = new NumericUpDown();
            channelInput = new NumericUpDown();
            passesInput = new NumericUpDown();
            pointsInput = new NumericUpDown();
            runButton = new Button();
            previewButton = new Button();
            caption_originalPath = new Label();
            caption_measuredPath = new Label();
            caption_outputPath = new Label();
            caption_unitInput = new Label();
            caption_rateInput = new Label();
            caption_channelInput = new Label();
            caption_passesInput = new Label();
            caption_pointsInput = new Label();
            plot = new ComparisonPlotControl();
            ((System.ComponentModel.ISupportInitialize)rateInput).BeginInit();
            ((System.ComponentModel.ISupportInitialize)channelInput).BeginInit();
            ((System.ComponentModel.ISupportInitialize)passesInput).BeginInit();
            ((System.ComponentModel.ISupportInitialize)pointsInput).BeginInit();
            SuspendLayout();
            root.SuspendLayout();
            options.SuspendLayout();
            body.SuspendLayout();
            root.Name = "root";
            title.Name = "title";
            options.Name = "options";
            body.Name = "body";
            status.Name = "status";
            originalPath.Name = "originalPath";
            originalBrowse.Name = "originalBrowse";
            measuredPath.Name = "measuredPath";
            measuredBrowse.Name = "measuredBrowse";
            outputPath.Name = "outputPath";
            outputBrowse.Name = "outputBrowse";
            unitInput.Name = "unitInput";
            rateInput.Name = "rateInput";
            channelInput.Name = "channelInput";
            passesInput.Name = "passesInput";
            pointsInput.Name = "pointsInput";
            runButton.Name = "runButton";
            previewButton.Name = "previewButton";
            caption_originalPath.Name = "caption_originalPath";
            caption_measuredPath.Name = "caption_measuredPath";
            caption_outputPath.Name = "caption_outputPath";
            caption_unitInput.Name = "caption_unitInput";
            caption_rateInput.Name = "caption_rateInput";
            caption_channelInput.Name = "caption_channelInput";
            caption_passesInput.Name = "caption_passesInput";
            caption_pointsInput.Name = "caption_pointsInput";
            plot.Name = "plot";
            root.Dock = DockStyle.Fill;
            root.Padding = new Padding(16);
            root.ColumnCount = 1;
            root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            root.RowCount = 4;
            root.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
            root.RowStyles.Add(new RowStyle(SizeType.Absolute, 220F));
            root.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            root.RowStyles.Add(new RowStyle(SizeType.Absolute, 58F));
            root.BackColor = Color.FromArgb(241, 245, 249);
            root.Controls.Add(title, 0, 0);
            root.Controls.Add(options, 0, 1);
            root.Controls.Add(body, 0, 2);
            root.Controls.Add(status, 0, 3);
            title.Text = "造波信号修正";
            title.Font = new Font("Microsoft YaHei UI", 16F, FontStyle.Bold);
            title.Dock = DockStyle.Fill;
            options.Dock = DockStyle.Fill;
            options.BackColor = Color.White;
            options.Padding = new Padding(8);
            options.AutoScroll = true;
            options.WrapContents = true;
            caption_originalPath.Text = "原造波信号";
            caption_originalPath.AutoSize = true;
            caption_originalPath.Margin = new Padding(6, 9, 3, 3);
            options.Controls.Add(caption_originalPath);
            originalPath.Margin = new Padding(3, 3, 8, 8);
            originalPath.Width = 410;
            originalPath.Text = "";
            originalPath.ReadOnly = true;
            originalPath.BackColor = Color.White;
            originalPath.BorderStyle = BorderStyle.FixedSingle;
            options.Controls.Add(originalPath);
            options.SetFlowBreak(originalPath, false);
            originalBrowse.Margin = new Padding(3, 3, 8, 8);
            originalBrowse.Text = "选择信号";
            originalBrowse.Size = new Size(125, 32);
            originalBrowse.FlatStyle = FlatStyle.Flat;
            originalBrowse.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            originalBrowse.BackColor = Color.FromArgb(248, 250, 252);
            options.Controls.Add(originalBrowse);
            options.SetFlowBreak(originalBrowse, true);
            caption_measuredPath.Text = "实测波浪文件";
            caption_measuredPath.AutoSize = true;
            caption_measuredPath.Margin = new Padding(6, 9, 3, 3);
            options.Controls.Add(caption_measuredPath);
            measuredPath.Margin = new Padding(3, 3, 8, 8);
            measuredPath.Width = 410;
            measuredPath.Text = "";
            measuredPath.ReadOnly = true;
            measuredPath.BackColor = Color.White;
            measuredPath.BorderStyle = BorderStyle.FixedSingle;
            options.Controls.Add(measuredPath);
            options.SetFlowBreak(measuredPath, false);
            measuredBrowse.Margin = new Padding(3, 3, 8, 8);
            measuredBrowse.Text = "选择实测文件";
            measuredBrowse.Size = new Size(125, 32);
            measuredBrowse.FlatStyle = FlatStyle.Flat;
            measuredBrowse.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            measuredBrowse.BackColor = Color.FromArgb(248, 250, 252);
            options.Controls.Add(measuredBrowse);
            options.SetFlowBreak(measuredBrowse, true);
            caption_outputPath.Text = "修正输出";
            caption_outputPath.AutoSize = true;
            caption_outputPath.Margin = new Padding(6, 9, 3, 3);
            options.Controls.Add(caption_outputPath);
            outputPath.Margin = new Padding(3, 3, 8, 8);
            outputPath.Width = 410;
            outputPath.Text = "";
            outputPath.ReadOnly = true;
            outputPath.BackColor = Color.White;
            outputPath.BorderStyle = BorderStyle.FixedSingle;
            options.Controls.Add(outputPath);
            options.SetFlowBreak(outputPath, false);
            outputBrowse.Margin = new Padding(3, 3, 8, 8);
            outputBrowse.Text = "保存路径";
            outputBrowse.Size = new Size(125, 32);
            outputBrowse.FlatStyle = FlatStyle.Flat;
            outputBrowse.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            outputBrowse.BackColor = Color.FromArgb(248, 250, 252);
            options.Controls.Add(outputBrowse);
            options.SetFlowBreak(outputBrowse, true);
            caption_unitInput.Text = "旧文件/程序单位";
            caption_unitInput.AutoSize = true;
            caption_unitInput.Margin = new Padding(6, 9, 3, 3);
            options.Controls.Add(caption_unitInput);
            unitInput.Margin = new Padding(3, 3, 8, 8);
            unitInput.DropDownStyle = ComboBoxStyle.DropDownList;
            unitInput.Width = 135;
            unitInput.Items.AddRange(new object[] { "mm", "m" });
            unitInput.SelectedIndex = 0;
            options.Controls.Add(unitInput);
            caption_rateInput.Text = "CSV频率(Hz)";
            caption_rateInput.AutoSize = true;
            caption_rateInput.Margin = new Padding(6, 9, 3, 3);
            options.Controls.Add(caption_rateInput);
            rateInput.Margin = new Padding(3, 3, 8, 8);
            rateInput.Width = 78;
            rateInput.Maximum = 1000M;
            rateInput.Minimum = 1M;
            rateInput.DecimalPlaces = 2;
            rateInput.Increment = 0.01M;
            rateInput.Value = 50M;
            options.Controls.Add(rateInput);
            caption_channelInput.Text = "依据通道";
            caption_channelInput.AutoSize = true;
            caption_channelInput.Margin = new Padding(6, 9, 3, 3);
            options.Controls.Add(caption_channelInput);
            channelInput.Margin = new Padding(3, 3, 8, 8);
            channelInput.Width = 78;
            channelInput.Maximum = 6M;
            channelInput.Minimum = 1M;
            channelInput.DecimalPlaces = 0;
            channelInput.Increment = 1M;
            channelInput.Value = 1M;
            options.Controls.Add(channelInput);
            caption_passesInput.Text = "光滑次数";
            caption_passesInput.AutoSize = true;
            caption_passesInput.Margin = new Padding(6, 9, 3, 3);
            options.Controls.Add(caption_passesInput);
            passesInput.Margin = new Padding(3, 3, 8, 8);
            passesInput.Width = 78;
            passesInput.Maximum = 20M;
            passesInput.Minimum = 0M;
            passesInput.DecimalPlaces = 0;
            passesInput.Increment = 1M;
            passesInput.Value = 7M;
            options.Controls.Add(passesInput);
            caption_pointsInput.Text = "光滑点数";
            caption_pointsInput.AutoSize = true;
            caption_pointsInput.Margin = new Padding(6, 9, 3, 3);
            options.Controls.Add(caption_pointsInput);
            pointsInput.Margin = new Padding(3, 3, 8, 8);
            pointsInput.Width = 78;
            pointsInput.Maximum = 101M;
            pointsInput.Minimum = 1M;
            pointsInput.DecimalPlaces = 0;
            pointsInput.Increment = 1M;
            pointsInput.Value = 3M;
            options.Controls.Add(pointsInput);
            runButton.Margin = new Padding(3, 3, 8, 8);
            runButton.Text = "修正并保存";
            runButton.Size = new Size(125, 32);
            runButton.FlatStyle = FlatStyle.Flat;
            runButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            runButton.BackColor = Color.FromArgb(248, 250, 252);
            runButton.BackColor = Color.FromArgb(29, 78, 216);
            runButton.ForeColor = Color.White;
            options.Controls.Add(runButton);
            previewButton.Margin = new Padding(3, 3, 8, 8);
            previewButton.Text = "新旧信号对比";
            previewButton.Size = new Size(125, 32);
            previewButton.FlatStyle = FlatStyle.Flat;
            previewButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            previewButton.BackColor = Color.FromArgb(248, 250, 252);
            options.Controls.Add(previewButton);
            body.Dock = DockStyle.Fill;
            body.ColumnCount = 1;
            body.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            body.RowCount = 1;
            body.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            plot.Dock = DockStyle.Fill;
            plot.MinimumSize = new Size(300, 180);
            plot.HorizontalCaption = "Time (s)";
            plot.VerticalCaption = "造波板位移(mm)";
            plot.FirstCaption = "原信号";
            plot.SecondCaption = "修正信号";
            body.Controls.Add(plot, 0, 0);
            status.Text = "调用旧WC-12.exe；仅处理文件，不自动下发PLC。失败时保留原文件。";
            status.Dock = DockStyle.Fill;
            status.AutoEllipsis = true;
            status.ForeColor = Color.FromArgb(71, 85, 105);
            Font = new Font("Microsoft YaHei UI", 9F);
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            AutoScroll = true;
            AutoScrollMinSize = new Size(1000, 580);
            Size = new Size(1104, 606);
            pagePanel.Name = "pagePanel";
            pagePanel.Dock = DockStyle.Fill;
            pagePanel.Controls.Add(root);
            Name = "SignalCorrectionPage";
            Controls.Add(pagePanel);
            body.ResumeLayout(false);
            options.ResumeLayout(false);
            options.PerformLayout();
            root.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)rateInput).EndInit();
            ((System.ComponentModel.ISupportInitialize)channelInput).EndInit();
            ((System.ComponentModel.ISupportInitialize)passesInput).EndInit();
            ((System.ComponentModel.ISupportInitialize)pointsInput).EndInit();
            ResumeLayout(false);
        }
    }
}
