namespace Page_switching.panel
{
    partial class SignalCorrectionPage
    {
        private Panel pagePanel;

        private System.ComponentModel.IContainer components = null;
        private TableLayoutPanel root;
        private Label title;
        private TableLayoutPanel options;
        private TableLayoutPanel parameters;
        private TableLayoutPanel unitGroup;
        private TableLayoutPanel rateGroup;
        private TableLayoutPanel channelGroup;
        private TableLayoutPanel passesGroup;
        private TableLayoutPanel pointsGroup;
        private TableLayoutPanel actions;
        private TableLayoutPanel body;
        private Label status;
        private TextBox originalPath;
        private Button originalBrowse;
        private TextBox measuredPath;
        private Button measuredBrowse;
        private TextBox outputPath;
        private Button outputBrowse;
        private ComboBox unitInput;
        private NumericUpDown rateInput;
        private NumericUpDown channelInput;
        private NumericUpDown passesInput;
        private NumericUpDown pointsInput;
        private Button runButton;
        private Button previewButton;
        private Label caption_originalPath;
        private Label caption_measuredPath;
        private Label caption_outputPath;
        private Label caption_unitInput;
        private Label caption_rateInput;
        private Label caption_channelInput;
        private Label caption_passesInput;
        private Label caption_pointsInput;
        private ComparisonPlotControl plot;

        protected override void Dispose(bool disposing)
        {
            if (disposing) components?.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            pagePanel = new Panel();
            components = new System.ComponentModel.Container();
            root = new TableLayoutPanel();
            title = new Label();
            options = new TableLayoutPanel();
            parameters = new TableLayoutPanel();
            unitGroup = new TableLayoutPanel();
            rateGroup = new TableLayoutPanel();
            channelGroup = new TableLayoutPanel();
            passesGroup = new TableLayoutPanel();
            pointsGroup = new TableLayoutPanel();
            actions = new TableLayoutPanel();
            body = new TableLayoutPanel();
            status = new Label();
            originalPath = new TextBox();
            originalBrowse = new Button();
            measuredPath = new TextBox();
            measuredBrowse = new Button();
            outputPath = new TextBox();
            outputBrowse = new Button();
            unitInput = new ComboBox();
            rateInput = new NumericUpDown();
            channelInput = new NumericUpDown();
            passesInput = new NumericUpDown();
            pointsInput = new NumericUpDown();
            runButton = new Button();
            previewButton = new Button();
            caption_originalPath = new Label();
            caption_measuredPath = new Label();
            caption_outputPath = new Label();
            caption_unitInput = new Label();
            caption_rateInput = new Label();
            caption_channelInput = new Label();
            caption_passesInput = new Label();
            caption_pointsInput = new Label();
            plot = new ComparisonPlotControl();
            ((System.ComponentModel.ISupportInitialize)rateInput).BeginInit();
            ((System.ComponentModel.ISupportInitialize)channelInput).BeginInit();
            ((System.ComponentModel.ISupportInitialize)passesInput).BeginInit();
            ((System.ComponentModel.ISupportInitialize)pointsInput).BeginInit();
            SuspendLayout();
            pagePanel.SuspendLayout();
            root.SuspendLayout();
            options.SuspendLayout();
            parameters.SuspendLayout();
            unitGroup.SuspendLayout();
            rateGroup.SuspendLayout();
            channelGroup.SuspendLayout();
            passesGroup.SuspendLayout();
            pointsGroup.SuspendLayout();
            actions.SuspendLayout();
            body.SuspendLayout();
            root.Name = "root";
            title.Name = "title";
            options.Name = "options";
            body.Name = "body";
            status.Name = "status";
            originalPath.Name = "originalPath";
            originalBrowse.Name = "originalBrowse";
            measuredPath.Name = "measuredPath";
            measuredBrowse.Name = "measuredBrowse";
            outputPath.Name = "outputPath";
            outputBrowse.Name = "outputBrowse";
            unitInput.Name = "unitInput";
            rateInput.Name = "rateInput";
            channelInput.Name = "channelInput";
            passesInput.Name = "passesInput";
            pointsInput.Name = "pointsInput";
            runButton.Name = "runButton";
            previewButton.Name = "previewButton";
            caption_originalPath.Name = "caption_originalPath";
            caption_measuredPath.Name = "caption_measuredPath";
            caption_outputPath.Name = "caption_outputPath";
            caption_unitInput.Name = "caption_unitInput";
            caption_rateInput.Name = "caption_rateInput";
            caption_channelInput.Name = "caption_channelInput";
            caption_passesInput.Name = "caption_passesInput";
            caption_pointsInput.Name = "caption_pointsInput";
            plot.Name = "plot";
            root.Dock = DockStyle.Fill;
            root.Margin = new Padding(0);
            root.Padding = new Padding(16);
            root.ColumnCount = 1;
            root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            root.RowCount = 4;
            root.RowStyles.Add(new RowStyle(SizeType.Absolute, 40F));
            root.RowStyles.Add(new RowStyle(SizeType.Absolute, 210F));
            root.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            root.RowStyles.Add(new RowStyle(SizeType.Absolute, 32F));
            root.BackColor = Color.FromArgb(241, 245, 249);
            root.Controls.Add(title, 0, 0);
            root.Controls.Add(options, 0, 1);
            root.Controls.Add(body, 0, 2);
            root.Controls.Add(status, 0, 3);
            title.Text = "造波信号修正";
            title.Font = new Font("Microsoft YaHei UI", 16F, FontStyle.Bold);
            title.Dock = DockStyle.Fill;
            title.Margin = new Padding(0);
            // 固定标签和浏览列，路径列随页面宽度伸缩，避免文件行错位或换行。
            options.Dock = DockStyle.Fill;
            options.Margin = new Padding(0);
            options.BackColor = Color.White;
            options.Padding = new Padding(8);
            options.ColumnCount = 3;
            options.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 112F));
            options.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            options.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 128F));
            options.RowCount = 5;
            options.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
            options.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
            options.RowStyles.Add(new RowStyle(SizeType.Absolute, 34F));
            options.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
            options.RowStyles.Add(new RowStyle(SizeType.Absolute, 36F));
            options.Controls.Add(caption_originalPath, 0, 0);
            options.Controls.Add(originalPath, 1, 0);
            options.Controls.Add(originalBrowse, 2, 0);
            options.Controls.Add(caption_measuredPath, 0, 1);
            options.Controls.Add(measuredPath, 1, 1);
            options.Controls.Add(measuredBrowse, 2, 1);
            options.Controls.Add(caption_outputPath, 0, 2);
            options.Controls.Add(outputPath, 1, 2);
            options.Controls.Add(outputBrowse, 2, 2);
            options.Controls.Add(parameters, 0, 3);
            options.SetColumnSpan(parameters, 3);
            options.Controls.Add(actions, 0, 4);
            options.SetColumnSpan(actions, 3);
            caption_originalPath.Text = "原造波信号";
            caption_originalPath.Dock = DockStyle.Fill;
            caption_originalPath.Margin = new Padding(0);
            caption_originalPath.TextAlign = ContentAlignment.MiddleLeft;
            originalPath.Anchor = AnchorStyles.Left | AnchorStyles.Right;
            originalPath.Margin = new Padding(0);
            originalPath.Text = "";
            originalPath.ReadOnly = true;
            originalPath.BackColor = Color.White;
            originalPath.BorderStyle = BorderStyle.FixedSingle;
            originalBrowse.Dock = DockStyle.Fill;
            originalBrowse.Margin = new Padding(8, 1, 0, 1);
            originalBrowse.Text = "选择信号";
            originalBrowse.FlatStyle = FlatStyle.Flat;
            originalBrowse.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            originalBrowse.BackColor = Color.FromArgb(248, 250, 252);
            caption_measuredPath.Text = "实测波浪文件";
            caption_measuredPath.Dock = DockStyle.Fill;
            caption_measuredPath.Margin = new Padding(0);
            caption_measuredPath.TextAlign = ContentAlignment.MiddleLeft;
            measuredPath.Anchor = AnchorStyles.Left | AnchorStyles.Right;
            measuredPath.Margin = new Padding(0);
            measuredPath.Text = "";
            measuredPath.ReadOnly = true;
            measuredPath.BackColor = Color.White;
            measuredPath.BorderStyle = BorderStyle.FixedSingle;
            measuredBrowse.Dock = DockStyle.Fill;
            measuredBrowse.Margin = new Padding(8, 1, 0, 1);
            measuredBrowse.Text = "选择实测文件";
            measuredBrowse.FlatStyle = FlatStyle.Flat;
            measuredBrowse.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            measuredBrowse.BackColor = Color.FromArgb(248, 250, 252);
            caption_outputPath.Text = "修正输出";
            caption_outputPath.Dock = DockStyle.Fill;
            caption_outputPath.Margin = new Padding(0);
            caption_outputPath.TextAlign = ContentAlignment.MiddleLeft;
            outputPath.Anchor = AnchorStyles.Left | AnchorStyles.Right;
            outputPath.Margin = new Padding(0);
            outputPath.Text = "";
            outputPath.ReadOnly = true;
            outputPath.BackColor = Color.White;
            outputPath.BorderStyle = BorderStyle.FixedSingle;
            outputBrowse.Dock = DockStyle.Fill;
            outputBrowse.Margin = new Padding(8, 1, 0, 1);
            outputBrowse.Text = "保存路径";
            outputBrowse.FlatStyle = FlatStyle.Flat;
            outputBrowse.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            outputBrowse.BackColor = Color.FromArgb(248, 250, 252);
            // 五个参数各占等宽列；标签在上、输入在下，缩放时仍保持成组对齐。
            parameters.Name = "parameters";
            parameters.Dock = DockStyle.Fill;
            parameters.Margin = new Padding(0);
            parameters.ColumnCount = 5;
            parameters.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
            parameters.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
            parameters.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
            parameters.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
            parameters.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 20F));
            parameters.RowCount = 1;
            parameters.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            parameters.Controls.Add(unitGroup, 0, 0);
            parameters.Controls.Add(rateGroup, 1, 0);
            parameters.Controls.Add(channelGroup, 2, 0);
            parameters.Controls.Add(passesGroup, 3, 0);
            parameters.Controls.Add(pointsGroup, 4, 0);
            unitGroup.Name = "unitGroup";
            unitGroup.Dock = DockStyle.Fill;
            unitGroup.Margin = new Padding(0, 0, 12, 0);
            unitGroup.ColumnCount = 1;
            unitGroup.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            unitGroup.RowCount = 2;
            unitGroup.RowStyles.Add(new RowStyle(SizeType.Absolute, 24F));
            unitGroup.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            unitGroup.Controls.Add(caption_unitInput, 0, 0);
            unitGroup.Controls.Add(unitInput, 0, 1);
            caption_unitInput.Text = "旧文件/程序单位";
            caption_unitInput.Dock = DockStyle.Fill;
            caption_unitInput.Margin = new Padding(0);
            caption_unitInput.TextAlign = ContentAlignment.MiddleLeft;
            unitInput.Dock = DockStyle.Fill;
            unitInput.Margin = new Padding(0, 0, 0, 4);
            unitInput.DropDownStyle = ComboBoxStyle.DropDownList;
            unitInput.Items.AddRange(new object[] { "mm", "m" });
            unitInput.SelectedIndex = 0;
            rateGroup.Name = "rateGroup";
            rateGroup.Dock = DockStyle.Fill;
            rateGroup.Margin = new Padding(0, 0, 12, 0);
            rateGroup.ColumnCount = 1;
            rateGroup.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            rateGroup.RowCount = 2;
            rateGroup.RowStyles.Add(new RowStyle(SizeType.Absolute, 24F));
            rateGroup.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            rateGroup.Controls.Add(caption_rateInput, 0, 0);
            rateGroup.Controls.Add(rateInput, 0, 1);
            caption_rateInput.Text = "CSV频率(Hz)";
            caption_rateInput.Dock = DockStyle.Fill;
            caption_rateInput.Margin = new Padding(0);
            caption_rateInput.TextAlign = ContentAlignment.MiddleLeft;
            rateInput.Dock = DockStyle.Fill;
            rateInput.Margin = new Padding(0, 0, 0, 4);
            rateInput.Maximum = 1000M;
            rateInput.Minimum = 1M;
            rateInput.DecimalPlaces = 2;
            rateInput.Increment = 0.01M;
            rateInput.Value = 50M;
            channelGroup.Name = "channelGroup";
            channelGroup.Dock = DockStyle.Fill;
            channelGroup.Margin = new Padding(0, 0, 12, 0);
            channelGroup.ColumnCount = 1;
            channelGroup.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            channelGroup.RowCount = 2;
            channelGroup.RowStyles.Add(new RowStyle(SizeType.Absolute, 24F));
            channelGroup.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            channelGroup.Controls.Add(caption_channelInput, 0, 0);
            channelGroup.Controls.Add(channelInput, 0, 1);
            caption_channelInput.Text = "依据通道";
            caption_channelInput.Dock = DockStyle.Fill;
            caption_channelInput.Margin = new Padding(0);
            caption_channelInput.TextAlign = ContentAlignment.MiddleLeft;
            channelInput.Dock = DockStyle.Fill;
            channelInput.Margin = new Padding(0, 0, 0, 4);
            channelInput.Maximum = 6M;
            channelInput.Minimum = 1M;
            channelInput.DecimalPlaces = 0;
            channelInput.Increment = 1M;
            channelInput.Value = 1M;
            passesGroup.Name = "passesGroup";
            passesGroup.Dock = DockStyle.Fill;
            passesGroup.Margin = new Padding(0, 0, 12, 0);
            passesGroup.ColumnCount = 1;
            passesGroup.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            passesGroup.RowCount = 2;
            passesGroup.RowStyles.Add(new RowStyle(SizeType.Absolute, 24F));
            passesGroup.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            passesGroup.Controls.Add(caption_passesInput, 0, 0);
            passesGroup.Controls.Add(passesInput, 0, 1);
            caption_passesInput.Text = "光滑次数";
            caption_passesInput.Dock = DockStyle.Fill;
            caption_passesInput.Margin = new Padding(0);
            caption_passesInput.TextAlign = ContentAlignment.MiddleLeft;
            passesInput.Dock = DockStyle.Fill;
            passesInput.Margin = new Padding(0, 0, 0, 4);
            passesInput.Maximum = 20M;
            passesInput.Minimum = 0M;
            passesInput.DecimalPlaces = 0;
            passesInput.Increment = 1M;
            passesInput.Value = 7M;
            pointsGroup.Name = "pointsGroup";
            pointsGroup.Dock = DockStyle.Fill;
            pointsGroup.Margin = new Padding(0);
            pointsGroup.ColumnCount = 1;
            pointsGroup.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            pointsGroup.RowCount = 2;
            pointsGroup.RowStyles.Add(new RowStyle(SizeType.Absolute, 24F));
            pointsGroup.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            pointsGroup.Controls.Add(caption_pointsInput, 0, 0);
            pointsGroup.Controls.Add(pointsInput, 0, 1);
            caption_pointsInput.Text = "光滑点数";
            caption_pointsInput.Dock = DockStyle.Fill;
            caption_pointsInput.Margin = new Padding(0);
            caption_pointsInput.TextAlign = ContentAlignment.MiddleLeft;
            pointsInput.Dock = DockStyle.Fill;
            pointsInput.Margin = new Padding(0, 0, 0, 4);
            pointsInput.Maximum = 101M;
            pointsInput.Minimum = 1M;
            pointsInput.DecimalPlaces = 0;
            pointsInput.Increment = 1M;
            pointsInput.Value = 3M;
            // 保留统一禁用入口 options；操作按钮在固定行中靠右，主操作置于最右侧。
            actions.Name = "actions";
            actions.Dock = DockStyle.Fill;
            actions.Margin = new Padding(0);
            actions.ColumnCount = 3;
            actions.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            actions.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 136F));
            actions.ColumnStyles.Add(new ColumnStyle(SizeType.Absolute, 136F));
            actions.RowCount = 1;
            actions.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            actions.Controls.Add(previewButton, 1, 0);
            actions.Controls.Add(runButton, 2, 0);
            runButton.Dock = DockStyle.Fill;
            runButton.Margin = new Padding(8, 2, 0, 2);
            runButton.Text = "修正并保存";
            runButton.FlatStyle = FlatStyle.Flat;
            runButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            runButton.BackColor = Color.FromArgb(29, 78, 216);
            runButton.ForeColor = Color.White;
            previewButton.Dock = DockStyle.Fill;
            previewButton.Margin = new Padding(8, 2, 0, 2);
            previewButton.Text = "新旧信号对比";
            previewButton.FlatStyle = FlatStyle.Flat;
            previewButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            previewButton.BackColor = Color.FromArgb(248, 250, 252);
            body.Dock = DockStyle.Fill;
            body.Margin = new Padding(0, 8, 0, 0);
            body.ColumnCount = 1;
            body.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            body.RowCount = 1;
            body.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            plot.Dock = DockStyle.Fill;
            plot.MinimumSize = new Size(300, 180);
            plot.HorizontalCaption = "Time (s)";
            plot.VerticalCaption = "造波板位移(mm)";
            plot.FirstCaption = "原信号";
            plot.SecondCaption = "修正信号";
            body.Controls.Add(plot, 0, 0);
            status.Text = "调用旧WC-12.exe；仅处理文件，不自动下发PLC。失败时保留原文件。";
            status.Dock = DockStyle.Fill;
            status.Margin = new Padding(0, 4, 0, 0);
            status.TextAlign = ContentAlignment.MiddleLeft;
            status.AutoEllipsis = true;
            status.ForeColor = Color.FromArgb(71, 85, 105);
            Font = new Font("Microsoft YaHei UI", 9F);
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            AutoScroll = true;
            AutoScrollMinSize = new Size(820, 560);
            Size = new Size(1104, 606);
            pagePanel.Name = "pagePanel";
            // 最小画布随 DPI 缩放，小视口通过页面滚动展示，避免图区挤入状态行。
            pagePanel.MinimumSize = new Size(820, 560);
            pagePanel.Dock = DockStyle.Fill;
            pagePanel.Controls.Add(root);
            Name = "SignalCorrectionPage";
            Controls.Add(pagePanel);
            body.ResumeLayout(false);
            actions.ResumeLayout(false);
            pointsGroup.ResumeLayout(false);
            pointsGroup.PerformLayout();
            passesGroup.ResumeLayout(false);
            passesGroup.PerformLayout();
            channelGroup.ResumeLayout(false);
            channelGroup.PerformLayout();
            rateGroup.ResumeLayout(false);
            rateGroup.PerformLayout();
            unitGroup.ResumeLayout(false);
            unitGroup.PerformLayout();
            parameters.ResumeLayout(false);
            options.ResumeLayout(false);
            options.PerformLayout();
            root.ResumeLayout(false);
            pagePanel.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)rateInput).EndInit();
            ((System.ComponentModel.ISupportInitialize)channelInput).EndInit();
            ((System.ComponentModel.ISupportInitialize)passesInput).EndInit();
            ((System.ComponentModel.ISupportInitialize)pointsInput).EndInit();
            ResumeLayout(false);
        }
    }
}
