namespace Page_switching.panel;

partial class WaveAnalysisPage
{
    private TableLayoutPanel root = null!;
    private Label title = null!;
    private FlowLayoutPanel options = null!;
    private TableLayoutPanel body = null!;
    private Label status = null!;
    private TextBox inputPath = null!;
    private Button browseButton = null!;
    private NumericUpDown channelInput = null!;
    private ComboBox unitInput = null!;
    private NumericUpDown rateInput = null!;
    private NumericUpDown heightInput = null!;
    private NumericUpDown periodInput = null!;
    private NumericUpDown gammaInput = null!;
    private ComboBox spectrumInput = null!;
    private NumericUpDown passesInput = null!;
    private NumericUpDown pointsInput = null!;
    private Button analyzeButton = null!;
    private Button exportSpectrumButton = null!;
    private Button exportElementsButton = null!;
    private Label caption_inputPath = null!;
    private Label caption_channelInput = null!;
    private Label caption_unitInput = null!;
    private Label caption_rateInput = null!;
    private Label caption_heightInput = null!;
    private Label caption_periodInput = null!;
    private Label caption_gammaInput = null!;
    private Label caption_spectrumInput = null!;
    private Label caption_passesInput = null!;
    private Label caption_pointsInput = null!;
    private ComparisonPlotControl plot = null!;
    private DataGridView elements = null!;
    private ComboBox methodInput = null!;
    private NumericUpDown depthInput = null!;
    private Label depthCaption = null!;
    private Label methodCaption = null!;
    private Button importResultsButton = null!;

    private void InitializeComponent()
    {
        root = new TableLayoutPanel();
        title = new Label();
        options = new FlowLayoutPanel();
        body = new TableLayoutPanel();
        status = new Label();
        inputPath = new TextBox();
        browseButton = new Button();
        channelInput = new NumericUpDown();
        unitInput = new ComboBox();
        rateInput = new NumericUpDown();
        heightInput = new NumericUpDown();
        periodInput = new NumericUpDown();
        gammaInput = new NumericUpDown();
        spectrumInput = new ComboBox();
        passesInput = new NumericUpDown();
        pointsInput = new NumericUpDown();
        analyzeButton = new Button();
        exportSpectrumButton = new Button();
        exportElementsButton = new Button();
        caption_inputPath = new Label();
        caption_channelInput = new Label();
        caption_unitInput = new Label();
        caption_rateInput = new Label();
        caption_heightInput = new Label();
        caption_periodInput = new Label();
        caption_gammaInput = new Label();
        caption_spectrumInput = new Label();
        caption_passesInput = new Label();
        caption_pointsInput = new Label();
        plot = new ComparisonPlotControl();
        elements = new DataGridView();
        methodInput = new ComboBox();
        depthInput = new NumericUpDown();
        depthCaption = new Label();
        methodCaption = new Label();
        importResultsButton = new Button();
        SuspendLayout();
        root.SuspendLayout();
        options.SuspendLayout();
        body.SuspendLayout();
        root.Name = "root";
        title.Name = "title";
        options.Name = "options";
        body.Name = "body";
        status.Name = "status";
        inputPath.Name = "inputPath";
        browseButton.Name = "browseButton";
        channelInput.Name = "channelInput";
        unitInput.Name = "unitInput";
        rateInput.Name = "rateInput";
        heightInput.Name = "heightInput";
        periodInput.Name = "periodInput";
        gammaInput.Name = "gammaInput";
        spectrumInput.Name = "spectrumInput";
        passesInput.Name = "passesInput";
        pointsInput.Name = "pointsInput";
        analyzeButton.Name = "analyzeButton";
        exportSpectrumButton.Name = "exportSpectrumButton";
        exportElementsButton.Name = "exportElementsButton";
        caption_inputPath.Name = "caption_inputPath";
        caption_channelInput.Name = "caption_channelInput";
        caption_unitInput.Name = "caption_unitInput";
        caption_rateInput.Name = "caption_rateInput";
        caption_heightInput.Name = "caption_heightInput";
        caption_periodInput.Name = "caption_periodInput";
        caption_gammaInput.Name = "caption_gammaInput";
        caption_spectrumInput.Name = "caption_spectrumInput";
        caption_passesInput.Name = "caption_passesInput";
        caption_pointsInput.Name = "caption_pointsInput";
        plot.Name = "plot";
        elements.Name = "elements";
        root.Dock = DockStyle.Fill;
        root.Padding = new Padding(16);
        root.ColumnCount = 1;
        root.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
        root.RowCount = 4;
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 44F));
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 220F));
        root.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        root.RowStyles.Add(new RowStyle(SizeType.Absolute, 58F));
        root.BackColor = Color.FromArgb(241, 245, 249);
        root.Controls.Add(title, 0, 0);
        root.Controls.Add(options, 0, 1);
        root.Controls.Add(body, 0, 2);
        root.Controls.Add(status, 0, 3);
        title.Text = "波浪统计与频谱对比";
        title.Font = new Font("Microsoft YaHei UI", 16F, FontStyle.Bold);
        title.Dock = DockStyle.Fill;
        options.Dock = DockStyle.Fill;
        options.BackColor = Color.White;
        options.Padding = new Padding(8);
        options.AutoScroll = true;
        options.WrapContents = true;
        caption_inputPath.Text = "实测文件";
        caption_inputPath.AutoSize = true;
        caption_inputPath.Margin = new Padding(6, 9, 3, 3);
        options.Controls.Add(caption_inputPath);
        inputPath.Margin = new Padding(3, 3, 8, 8);
        inputPath.Width = 410;
        inputPath.Text = "";
        inputPath.ReadOnly = true;
        inputPath.BackColor = Color.White;
        inputPath.BorderStyle = BorderStyle.FixedSingle;
        options.Controls.Add(inputPath);
        options.SetFlowBreak(inputPath, false);
        browseButton.Margin = new Padding(3, 3, 8, 8);
        browseButton.Text = "选择文件";
        browseButton.Size = new Size(125, 32);
        browseButton.FlatStyle = FlatStyle.Flat;
        browseButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
        browseButton.BackColor = Color.FromArgb(248, 250, 252);
        options.Controls.Add(browseButton);
        caption_channelInput.Text = "通道";
        caption_channelInput.AutoSize = true;
        caption_channelInput.Margin = new Padding(6, 9, 3, 3);
        options.Controls.Add(caption_channelInput);
        channelInput.Margin = new Padding(3, 3, 8, 8);
        channelInput.Width = 78;
        channelInput.Maximum = 6M;
        channelInput.Minimum = 1M;
        channelInput.DecimalPlaces = 0;
        channelInput.Increment = 1M;
        channelInput.Value = 1M;
        options.Controls.Add(channelInput);
        caption_unitInput.Text = "旧文件单位";
        caption_unitInput.AutoSize = true;
        caption_unitInput.Margin = new Padding(6, 9, 3, 3);
        options.Controls.Add(caption_unitInput);
        unitInput.Margin = new Padding(3, 3, 8, 8);
        unitInput.DropDownStyle = ComboBoxStyle.DropDownList;
        unitInput.Width = 135;
        unitInput.Items.AddRange(new object[] { "mm", "m" });
        unitInput.SelectedIndex = 0;
        options.Controls.Add(unitInput);
        caption_rateInput.Text = "CSV频率(Hz)";
        caption_rateInput.AutoSize = true;
        caption_rateInput.Margin = new Padding(6, 9, 3, 3);
        options.Controls.Add(caption_rateInput);
        rateInput.Margin = new Padding(3, 3, 8, 8);
        rateInput.Width = 78;
        rateInput.Maximum = 1000M;
        rateInput.Minimum = 1M;
        rateInput.DecimalPlaces = 2;
        rateInput.Increment = 0.01M;
        rateInput.Value = 50M;
        options.Controls.Add(rateInput);
        caption_heightInput.Text = "理论波高(m)";
        caption_heightInput.AutoSize = true;
        caption_heightInput.Margin = new Padding(6, 9, 3, 3);
        options.Controls.Add(caption_heightInput);
        heightInput.Margin = new Padding(3, 3, 8, 8);
        heightInput.Width = 78;
        heightInput.Maximum = 10M;
        heightInput.Minimum = 0.001M;
        heightInput.DecimalPlaces = 3;
        heightInput.Increment = 0.01M;
        heightInput.Value = 0.05M;
        options.Controls.Add(heightInput);
        caption_periodInput.Text = "理论周期(s)";
        caption_periodInput.AutoSize = true;
        caption_periodInput.Margin = new Padding(6, 9, 3, 3);
        options.Controls.Add(caption_periodInput);
        periodInput.Margin = new Padding(3, 3, 8, 8);
        periodInput.Width = 78;
        periodInput.Maximum = 100M;
        periodInput.Minimum = 0.01M;
        periodInput.DecimalPlaces = 3;
        periodInput.Increment = 0.01M;
        periodInput.Value = 1.5M;
        options.Controls.Add(periodInput);
        caption_gammaInput.Text = "谱峰因子";
        caption_gammaInput.AutoSize = true;
        caption_gammaInput.Margin = new Padding(6, 9, 3, 3);
        options.Controls.Add(caption_gammaInput);
        gammaInput.Margin = new Padding(3, 3, 8, 8);
        gammaInput.Width = 78;
        gammaInput.Maximum = 20M;
        gammaInput.Minimum = 0.01M;
        gammaInput.DecimalPlaces = 2;
        gammaInput.Increment = 0.01M;
        gammaInput.Value = 3.3M;
        options.Controls.Add(gammaInput);
        caption_spectrumInput.Text = "理论谱";
        caption_spectrumInput.AutoSize = true;
        caption_spectrumInput.Margin = new Padding(6, 9, 3, 3);
        options.Controls.Add(caption_spectrumInput);
        spectrumInput.Margin = new Padding(3, 3, 8, 8);
        spectrumInput.DropDownStyle = ComboBoxStyle.DropDownList;
        spectrumInput.Width = 135;
        spectrumInput.Items.AddRange(new object[] { "JONSWAP", "P-M", "B谱", "ITTC", "规范谱", "Scott", "Darbyshire", "Wallops" });
        spectrumInput.SelectedIndex = 0;
        options.Controls.Add(spectrumInput);
        caption_passesInput.Text = "光滑次数";
        caption_passesInput.AutoSize = true;
        caption_passesInput.Margin = new Padding(6, 9, 3, 3);
        options.Controls.Add(caption_passesInput);
        passesInput.Margin = new Padding(3, 3, 8, 8);
        passesInput.Width = 78;
        passesInput.Maximum = 20M;
        passesInput.Minimum = 0M;
        passesInput.DecimalPlaces = 0;
        passesInput.Increment = 1M;
        passesInput.Value = 1M;
        options.Controls.Add(passesInput);
        caption_pointsInput.Text = "光滑点数";
        caption_pointsInput.AutoSize = true;
        caption_pointsInput.Margin = new Padding(6, 9, 3, 3);
        options.Controls.Add(caption_pointsInput);
        pointsInput.Margin = new Padding(3, 3, 8, 8);
        pointsInput.Width = 78;
        pointsInput.Maximum = 101M;
        pointsInput.Minimum = 1M;
        pointsInput.DecimalPlaces = 0;
        pointsInput.Increment = 1M;
        pointsInput.Value = 3M;
        options.Controls.Add(pointsInput);
        analyzeButton.Margin = new Padding(3, 3, 8, 8);
        analyzeButton.Text = "统计分析";
        analyzeButton.Size = new Size(125, 32);
        analyzeButton.FlatStyle = FlatStyle.Flat;
        analyzeButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
        analyzeButton.BackColor = Color.FromArgb(248, 250, 252);
        analyzeButton.BackColor = Color.FromArgb(29, 78, 216);
        analyzeButton.ForeColor = Color.White;
        options.Controls.Add(analyzeButton);
        exportSpectrumButton.Margin = new Padding(3, 3, 8, 8);
        exportSpectrumButton.Text = "导出频谱";
        exportSpectrumButton.Size = new Size(125, 32);
        exportSpectrumButton.FlatStyle = FlatStyle.Flat;
        exportSpectrumButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
        exportSpectrumButton.BackColor = Color.FromArgb(248, 250, 252);
        options.Controls.Add(exportSpectrumButton);
        exportElementsButton.Margin = new Padding(3, 3, 8, 8);
        exportElementsButton.Text = "导出波浪要素";
        exportElementsButton.Size = new Size(125, 32);
        exportElementsButton.FlatStyle = FlatStyle.Flat;
        exportElementsButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
        exportElementsButton.BackColor = Color.FromArgb(248, 250, 252);
        options.Controls.Add(exportElementsButton);
        options.SetFlowBreak(exportElementsButton, true);
        exportSpectrumButton.Enabled = false;
        exportElementsButton.Enabled = false;
        options.SetFlowBreak(browseButton, true);
        methodCaption.Text = "分析方式";
        methodCaption.AutoSize = true;
        methodCaption.Margin = new Padding(6, 9, 3, 3);
        methodInput.Name = "methodInput";
        methodInput.DropDownStyle = ComboBoxStyle.DropDownList;
        methodInput.Width = 180;
        methodInput.Items.AddRange(new object[] { "内置FFT", "旧WaveTJU程序" });
        methodInput.SelectedIndex = 0;
        methodInput.Margin = new Padding(3, 3, 8, 8);
        depthCaption.Text = "水深(m)";
        depthCaption.AutoSize = true;
        depthCaption.Margin = new Padding(6, 9, 3, 3);
        depthInput.Name = "depthInput";
        depthInput.Maximum = 100M;
        depthInput.Minimum = 0.001M;
        depthInput.DecimalPlaces = 3;
        depthInput.Value = 0.6M;
        depthInput.Width = 78;
        importResultsButton.Name = "importResultsButton";
        importResultsButton.Text = "导入旧分析结果";
        importResultsButton.Size = new Size(140, 32);
        importResultsButton.FlatStyle = FlatStyle.Flat;
        importResultsButton.BackColor = Color.FromArgb(248, 250, 252);
        options.Controls.Add(methodCaption);
        options.Controls.Add(methodInput);
        options.Controls.Add(depthCaption);
        options.Controls.Add(depthInput);
        options.Controls.Add(importResultsButton);
        body.Dock = DockStyle.Fill;
        body.ColumnCount = 2;
        body.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 70F));
        body.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 30F));
        body.RowCount = 1;
        body.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
        plot.Dock = DockStyle.Fill;
        plot.MinimumSize = new Size(300, 180);
        body.Controls.Add(plot, 0, 0);
        elements.Dock = DockStyle.Fill;
        elements.AllowUserToAddRows = false;
        elements.AllowUserToDeleteRows = false;
        elements.ReadOnly = true;
        elements.RowHeadersVisible = false;
        elements.BackgroundColor = Color.White;
        elements.BorderStyle = BorderStyle.None;
        elements.AutoSizeColumnsMode = DataGridViewAutoSizeColumnsMode.Fill;
        elements.EnableHeadersVisualStyles = false;
        elements.ColumnHeadersDefaultCellStyle.BackColor = Color.FromArgb(241, 245, 249);
        elements.DefaultCellStyle.SelectionBackColor = Color.FromArgb(219, 234, 254);
        elements.DefaultCellStyle.SelectionForeColor = Color.FromArgb(15, 23, 42);
        elements.Columns.Add("element", "要素");
        elements.Columns.Add("value", "值");
        body.Controls.Add(elements, 1, 0);
        status.Text = "本地会话采用记录的频率；外部采集CSV采用上方频率。旧文件单位需与原标定单位一致。";
        status.Dock = DockStyle.Fill;
        status.AutoEllipsis = true;
        status.ForeColor = Color.FromArgb(71, 85, 105);
        Font = new Font("Microsoft YaHei UI", 9F);
        AutoScaleDimensions = new SizeF(96F, 96F);
        AutoScaleMode = AutoScaleMode.Dpi;
        AutoScroll = true;
        AutoScrollMinSize = new Size(1000, 580);
        Size = new Size(1104, 606);
        Controls.Add(root);
        body.ResumeLayout(false);
        options.ResumeLayout(false);
        options.PerformLayout();
        root.ResumeLayout(false);
        ResumeLayout(false);
    }
}
