namespace Page_switching.panel
{
    partial class Wave_Height_Meter
    {
        private Panel pagePanel;

        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && components != null) components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            pagePanel = new Panel();
            SuspendLayout();
            rootLayout = new TableLayoutPanel();
            rootLayout.BackColor = Color.FromArgb(241, 245, 249);
            rootLayout.ColumnCount = 1;
            rootLayout.Dock = DockStyle.Fill;
            rootLayout.Name = "rootLayout";
            rootLayout.AutoScroll = false;
            rootLayout.Padding = new Padding(16);
            rootLayout.RowCount = 5;
            rootLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));

            rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 50F));
            rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 112F));
            rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 64F));
            rootLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 96F));
            rootLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            headerPanel = new Panel();
            headerPanel.Dock = DockStyle.Fill;
            headerPanel.Margin = new Padding(0, 0, 0, 8);
            headerPanel.Name = "headerPanel";
            titleLabel = new Label();
            titleLabel.AutoSize = true;
            titleLabel.Font = new Font("Microsoft YaHei UI", 16F, FontStyle.Bold);
            titleLabel.ForeColor = Color.FromArgb(15, 23, 42);
            titleLabel.Location = new Point(0, 0);
            titleLabel.Name = "titleLabel";
            titleLabel.Text = "浪高仪监测";
            headerPanel.Controls.Add(titleLabel);
            subtitleLabel = new Label();
            subtitleLabel.AutoSize = true;
            subtitleLabel.Font = new Font("Microsoft YaHei UI", 8.5F);
            subtitleLabel.ForeColor = Color.FromArgb(100, 116, 139);
            subtitleLabel.Location = new Point(0, 30);
            subtitleLabel.Name = "subtitleLabel";
            subtitleLabel.Text = "TCP 采集 · 通道 1 · 仪器原始计数";
            headerPanel.Controls.Add(subtitleLabel);
            rootLayout.Controls.Add(headerPanel, 0, 0);
            connectionCard = new Panel();
            connectionCard.BackColor = Color.White;
            connectionCard.BorderStyle = BorderStyle.None;
            connectionCard.Dock = DockStyle.Fill;
            connectionCard.Margin = new Padding(0, 4, 0, 4);
            connectionCard.Name = "connectionCard";
            connectionCard.Padding = new Padding(14, 10, 14, 10);
            connectionLayout = new TableLayoutPanel();
            connectionLayout.ColumnCount = 1;
            connectionLayout.Dock = DockStyle.Fill;
            connectionLayout.Margin = new Padding(0);
            connectionLayout.Name = "connectionLayout";
            connectionLayout.RowCount = 2;
            connectionCard.Controls.Add(connectionLayout);
            connectionLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));

            connectionLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 56F));
            connectionLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            connectionSettings = new FlowLayoutPanel();
            connectionSettings.AutoScroll = true;
            connectionSettings.Dock = DockStyle.Fill;
            connectionSettings.FlowDirection = FlowDirection.LeftToRight;
            connectionSettings.Margin = new Padding(0);
            connectionSettings.Name = "connectionSettings";
            connectionSettings.WrapContents = false;
            ipField = new Panel();
            ipField.Margin = new Padding(0, 0, 8, 0);
            ipField.Name = "ipField";
            ipField.Size = new Size(170, 54);
            connectionSettings.Controls.Add(ipField);
            ipCaption = new Label();
            ipCaption.AutoSize = true;
            ipCaption.Font = new Font("Microsoft YaHei UI", 8F);
            ipCaption.ForeColor = Color.FromArgb(71, 85, 105);
            ipCaption.Location = new Point(0, 0);
            ipCaption.Name = "ipCaption";
            ipCaption.Text = "设备 IP";
            ipField.Controls.Add(ipCaption);
            _ipAddressInput = new TextBox();
            _ipAddressInput.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            _ipAddressInput.BorderStyle = BorderStyle.FixedSingle;
            _ipAddressInput.Font = new Font("Microsoft YaHei UI", 9F);
            _ipAddressInput.Location = new Point(0, 23);
            _ipAddressInput.BackColor = Color.White;
            _ipAddressInput.ForeColor = Color.FromArgb(15, 23, 42);
            _ipAddressInput.Name = "_ipAddressInput";
            _ipAddressInput.Size = new Size(166, 27);
            _ipAddressInput.TabIndex = 0;
            _ipAddressInput.Text = "192.168.0.7";
            ipField.Controls.Add(_ipAddressInput);
            portField = new Panel();
            portField.Margin = new Padding(0, 0, 8, 0);
            portField.Name = "portField";
            portField.Size = new Size(80, 54);
            connectionSettings.Controls.Add(portField);
            portCaption = new Label();
            portCaption.AutoSize = true;
            portCaption.Font = new Font("Microsoft YaHei UI", 8F);
            portCaption.ForeColor = Color.FromArgb(71, 85, 105);
            portCaption.Location = new Point(0, 0);
            portCaption.Name = "portCaption";
            portCaption.Text = "端口";
            portField.Controls.Add(portCaption);
            _portInput = new NumericUpDown();
            _portInput.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            _portInput.BorderStyle = BorderStyle.FixedSingle;
            _portInput.Font = new Font("Microsoft YaHei UI", 9F);
            _portInput.Location = new Point(0, 23);
            _portInput.BackColor = Color.White;
            _portInput.ForeColor = Color.FromArgb(15, 23, 42);
            _portInput.Name = "_portInput";
            _portInput.Size = new Size(76, 27);
            _portInput.TabIndex = 1;
            _portInput.Maximum = 65535;
            _portInput.Minimum = 1;
            _portInput.Value = 502;
            portField.Controls.Add(_portInput);
            sampleRateField = new Panel();
            sampleRateField.Margin = new Padding(0, 0, 8, 0);
            sampleRateField.Name = "sampleRateField";
            sampleRateField.Size = new Size(110, 54);
            connectionSettings.Controls.Add(sampleRateField);
            sampleRateCaption = new Label();
            sampleRateCaption.AutoSize = true;
            sampleRateCaption.Font = new Font("Microsoft YaHei UI", 8F);
            sampleRateCaption.ForeColor = Color.FromArgb(71, 85, 105);
            sampleRateCaption.Location = new Point(0, 0);
            sampleRateCaption.Name = "sampleRateCaption";
            sampleRateCaption.Text = "采样频率 (Hz)";
            sampleRateField.Controls.Add(sampleRateCaption);
            _sampleRateInput = new NumericUpDown();
            _sampleRateInput.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            _sampleRateInput.BorderStyle = BorderStyle.FixedSingle;
            _sampleRateInput.Font = new Font("Microsoft YaHei UI", 9F);
            _sampleRateInput.Location = new Point(0, 23);
            _sampleRateInput.BackColor = Color.White;
            _sampleRateInput.ForeColor = Color.FromArgb(15, 23, 42);
            _sampleRateInput.Name = "_sampleRateInput";
            _sampleRateInput.Size = new Size(106, 27);
            _sampleRateInput.TabIndex = 2;
            _sampleRateInput.Maximum = 50;
            _sampleRateInput.Minimum = 2;
            _sampleRateInput.Value = 50;
            sampleRateField.Controls.Add(_sampleRateInput);
            sampleLimitField = new Panel();
            sampleLimitField.Margin = new Padding(0, 0, 8, 0);
            sampleLimitField.Name = "sampleLimitField";
            sampleLimitField.Size = new Size(95, 54);
            connectionSettings.Controls.Add(sampleLimitField);
            sampleLimitCaption = new Label();
            sampleLimitCaption.AutoSize = true;
            sampleLimitCaption.Font = new Font("Microsoft YaHei UI", 8F);
            sampleLimitCaption.Location = new Point(0, 0);
            sampleLimitCaption.Name = "sampleLimitCaption";
            sampleLimitCaption.Text = "采样点数";
            sampleLimitField.Controls.Add(sampleLimitCaption);
            _sampleLimitInput = new NumericUpDown();
            _sampleLimitInput.Location = new Point(0, 23);
            _sampleLimitInput.Maximum = 10000000;
            _sampleLimitInput.Minimum = 1;
            _sampleLimitInput.BackColor = Color.White;
            _sampleLimitInput.ForeColor = Color.FromArgb(15, 23, 42);
            _sampleLimitInput.Name = "_sampleLimitInput";
            _sampleLimitInput.BorderStyle = BorderStyle.FixedSingle;
            _sampleLimitInput.Size = new Size(91, 27);
            _sampleLimitInput.Value = 4096;
            sampleLimitField.Controls.Add(_sampleLimitInput);
            _connectButton = new Button();
            _connectButton.BackColor = Color.FromArgb(29, 78, 216);
            _connectButton.Cursor = Cursors.Hand;
            _connectButton.FlatStyle = FlatStyle.Flat;
            _connectButton.Font = new Font("Microsoft YaHei UI", 8.5F, FontStyle.Bold);
            _connectButton.ForeColor = Color.White;
            _connectButton.Margin = new Padding(0, 20, 6, 0);
            _connectButton.Name = "_connectButton";
            _connectButton.Size = new Size(104, 34);
            _connectButton.TabIndex = 3;
            _connectButton.Text = "连接并采集";
            _connectButton.UseVisualStyleBackColor = false;
            connectionSettings.Controls.Add(_connectButton);
            _connectButton.FlatAppearance.BorderSize = 0;
            _connectButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(30, 64, 175);
            _connectButton.Click += ConnectButton_Click;
            _disconnectButton = new Button();
            _disconnectButton.BackColor = Color.FromArgb(248, 250, 252);
            _disconnectButton.Cursor = Cursors.Hand;
            _disconnectButton.FlatStyle = FlatStyle.Flat;
            _disconnectButton.Font = new Font("Microsoft YaHei UI", 8.5F, FontStyle.Bold);
            _disconnectButton.ForeColor = Color.FromArgb(15, 23, 42);
            _disconnectButton.Margin = new Padding(0, 20, 6, 0);
            _disconnectButton.Name = "_disconnectButton";
            _disconnectButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(226, 232, 240);
            _disconnectButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            _disconnectButton.Size = new Size(100, 34);
            _disconnectButton.TabIndex = 4;
            _disconnectButton.Text = "停止并断开";
            _disconnectButton.UseVisualStyleBackColor = false;
            connectionSettings.Controls.Add(_disconnectButton);
            _disconnectButton.FlatAppearance.BorderSize = 1;
            _disconnectButton.Click += DisconnectButton_Click;
            _disconnectButton.Enabled = false;
            _saveSettingsButton = new Button();
            _saveSettingsButton.BackColor = Color.FromArgb(248, 250, 252);
            _saveSettingsButton.Cursor = Cursors.Hand;
            _saveSettingsButton.FlatStyle = FlatStyle.Flat;
            _saveSettingsButton.Font = new Font("Microsoft YaHei UI", 8.5F, FontStyle.Bold);
            _saveSettingsButton.ForeColor = Color.FromArgb(15, 23, 42);
            _saveSettingsButton.Margin = new Padding(0, 20, 6, 0);
            _saveSettingsButton.Name = "_saveSettingsButton";
            _saveSettingsButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(226, 232, 240);
            _saveSettingsButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            _saveSettingsButton.Size = new Size(88, 34);
            _saveSettingsButton.TabIndex = 5;
            _saveSettingsButton.Text = "保存参数";
            _saveSettingsButton.UseVisualStyleBackColor = false;
            connectionSettings.Controls.Add(_saveSettingsButton);
            _saveSettingsButton.FlatAppearance.BorderSize = 1;
            _saveSettingsButton.Click += SaveSettingsButton_Click;
            connectionLayout.Controls.Add(connectionSettings, 0, 0);
            connectionStatusPanel = new Panel();
            connectionStatusPanel.Dock = DockStyle.Fill;
            connectionStatusPanel.Margin = new Padding(0);
            connectionStatusPanel.Name = "connectionStatusPanel";
            connectionStatusCaption = new Label();
            connectionStatusCaption.AutoSize = true;
            connectionStatusCaption.Font = new Font("Microsoft YaHei UI", 8.5F);
            connectionStatusCaption.ForeColor = Color.FromArgb(71, 85, 105);
            connectionStatusCaption.Location = new Point(0, 5);
            connectionStatusCaption.Name = "connectionStatusCaption";
            connectionStatusCaption.Text = "连接状态";
            connectionStatusPanel.Controls.Add(connectionStatusCaption);
            _connectionStatusLabel = new Label();
            _connectionStatusLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            _connectionStatusLabel.AutoEllipsis = true;
            _connectionStatusLabel.Font = new Font("Microsoft YaHei UI", 9F);
            _connectionStatusLabel.ForeColor = Color.FromArgb(100, 116, 139);
            _connectionStatusLabel.Location = new Point(78, 4);
            _connectionStatusLabel.Name = "_connectionStatusLabel";
            _connectionStatusLabel.Size = new Size(780, 24);
            _connectionStatusLabel.Text = "设备未连接";
            connectionStatusPanel.Controls.Add(_connectionStatusLabel);
            connectionLayout.Controls.Add(connectionStatusPanel, 0, 1);
            rootLayout.Controls.Add(connectionCard, 0, 1);
            channelStatusPanel = new FlowLayoutPanel();
            channelStatusPanel.Dock = DockStyle.Fill;
            channelStatusPanel.Margin = new Padding(0, 4, 0, 4);
            channelStatusPanel.Name = "channelStatusPanel";
            channelStatusPanel.WrapContents = false;
            channelStatusPanel.AutoScroll = true;
            channel1Selector = new CheckBox();
            channel1Selector.Appearance = Appearance.Button;
            channel1Selector.BackColor = Color.White;
            channel1Selector.Checked = true;
            channel1Selector.Enabled = true;
            channel1Selector.FlatStyle = FlatStyle.Flat;
            channel1Selector.Font = new Font("Microsoft YaHei UI", 9F);
            channel1Selector.ForeColor = Color.FromArgb(15, 23, 42);
            channel1Selector.Margin = new Padding(0, 0, 8, 0);
            channel1Selector.Name = "channel1Selector";
            channel1Selector.FlatAppearance.CheckedBackColor = Color.FromArgb(219, 234, 254);
            channel1Selector.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            channel1Selector.Size = new Size(130, 56);
            channel1Selector.Text = "CH1\r\n等待采集";
            channel1Selector.TextAlign = ContentAlignment.MiddleCenter;
            channelStatusPanel.Controls.Add(channel1Selector);
            channel2Selector = new CheckBox();
            channel2Selector.Appearance = Appearance.Button;
            channel2Selector.BackColor = Color.White;
            channel2Selector.Checked = false;
            channel2Selector.Enabled = false;
            channel2Selector.FlatStyle = FlatStyle.Flat;
            channel2Selector.Font = new Font("Microsoft YaHei UI", 9F);
            channel2Selector.ForeColor = Color.FromArgb(100, 116, 139);
            channel2Selector.Margin = new Padding(0, 0, 8, 0);
            channel2Selector.Name = "channel2Selector";
            channel2Selector.FlatAppearance.CheckedBackColor = Color.FromArgb(219, 234, 254);
            channel2Selector.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            channel2Selector.Size = new Size(130, 56);
            channel2Selector.Text = "CH2\r\n待协议验证";
            channel2Selector.TextAlign = ContentAlignment.MiddleCenter;
            channelStatusPanel.Controls.Add(channel2Selector);
            channel3Selector = new CheckBox();
            channel3Selector.Appearance = Appearance.Button;
            channel3Selector.BackColor = Color.White;
            channel3Selector.Checked = false;
            channel3Selector.Enabled = false;
            channel3Selector.FlatStyle = FlatStyle.Flat;
            channel3Selector.Font = new Font("Microsoft YaHei UI", 9F);
            channel3Selector.ForeColor = Color.FromArgb(100, 116, 139);
            channel3Selector.Margin = new Padding(0, 0, 8, 0);
            channel3Selector.Name = "channel3Selector";
            channel3Selector.FlatAppearance.CheckedBackColor = Color.FromArgb(219, 234, 254);
            channel3Selector.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            channel3Selector.Size = new Size(130, 56);
            channel3Selector.Text = "CH3\r\n待协议验证";
            channel3Selector.TextAlign = ContentAlignment.MiddleCenter;
            channelStatusPanel.Controls.Add(channel3Selector);
            channel4Selector = new CheckBox();
            channel4Selector.Appearance = Appearance.Button;
            channel4Selector.BackColor = Color.White;
            channel4Selector.Checked = false;
            channel4Selector.Enabled = false;
            channel4Selector.FlatStyle = FlatStyle.Flat;
            channel4Selector.Font = new Font("Microsoft YaHei UI", 9F);
            channel4Selector.ForeColor = Color.FromArgb(100, 116, 139);
            channel4Selector.Margin = new Padding(0, 0, 8, 0);
            channel4Selector.Name = "channel4Selector";
            channel4Selector.FlatAppearance.CheckedBackColor = Color.FromArgb(219, 234, 254);
            channel4Selector.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            channel4Selector.Size = new Size(130, 56);
            channel4Selector.Text = "CH4\r\n待协议验证";
            channel4Selector.TextAlign = ContentAlignment.MiddleCenter;
            channelStatusPanel.Controls.Add(channel4Selector);
            channel5Selector = new CheckBox();
            channel5Selector.Appearance = Appearance.Button;
            channel5Selector.BackColor = Color.White;
            channel5Selector.Checked = false;
            channel5Selector.Enabled = false;
            channel5Selector.FlatStyle = FlatStyle.Flat;
            channel5Selector.Font = new Font("Microsoft YaHei UI", 9F);
            channel5Selector.ForeColor = Color.FromArgb(100, 116, 139);
            channel5Selector.Margin = new Padding(0, 0, 8, 0);
            channel5Selector.Name = "channel5Selector";
            channel5Selector.FlatAppearance.CheckedBackColor = Color.FromArgb(219, 234, 254);
            channel5Selector.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            channel5Selector.Size = new Size(130, 56);
            channel5Selector.Text = "CH5\r\n待协议验证";
            channel5Selector.TextAlign = ContentAlignment.MiddleCenter;
            channelStatusPanel.Controls.Add(channel5Selector);
            channel6Selector = new CheckBox();
            channel6Selector.Appearance = Appearance.Button;
            channel6Selector.BackColor = Color.White;
            channel6Selector.Checked = false;
            channel6Selector.Enabled = false;
            channel6Selector.FlatStyle = FlatStyle.Flat;
            channel6Selector.Font = new Font("Microsoft YaHei UI", 9F);
            channel6Selector.ForeColor = Color.FromArgb(100, 116, 139);
            channel6Selector.Margin = new Padding(0, 0, 8, 0);
            channel6Selector.Name = "channel6Selector";
            channel6Selector.FlatAppearance.CheckedBackColor = Color.FromArgb(219, 234, 254);
            channel6Selector.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            channel6Selector.Size = new Size(130, 56);
            channel6Selector.Text = "CH6\r\n待协议验证";
            channel6Selector.TextAlign = ContentAlignment.MiddleCenter;
            channelStatusPanel.Controls.Add(channel6Selector);
            rootLayout.Controls.Add(channelStatusPanel, 0, 2);
            readoutLayout = new TableLayoutPanel();
            readoutLayout.ColumnCount = 3;
            readoutLayout.Dock = DockStyle.Fill;
            readoutLayout.Margin = new Padding(0, 4, 0, 4);
            readoutLayout.Name = "readoutLayout";
            readoutLayout.RowCount = 1;
            readoutLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
            readoutLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.333F));
            readoutLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 33.334F));
            readoutLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            latestValueCard = new Panel();
            latestValueCard.BackColor = Color.White;
            latestValueCard.BorderStyle = BorderStyle.None;
            latestValueCard.Dock = DockStyle.Fill;
            latestValueCard.Margin = new Padding(4);
            latestValueCard.Name = "latestValueCard";
            latestValueCard.Padding = new Padding(16, 10, 12, 8);
            latestValueCaption = new Label();
            latestValueCaption.AutoSize = true;
            latestValueCaption.Font = new Font("Microsoft YaHei UI", 8.5F);
            latestValueCaption.ForeColor = Color.FromArgb(100, 116, 139);
            latestValueCaption.Location = new Point(12, 6);
            latestValueCaption.Name = "latestValueCaption";
            latestValueCaption.Text = "当前原始值";
            latestValueCard.Controls.Add(latestValueCaption);
            _latestValueLabel = new Label();
            _latestValueLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            _latestValueLabel.AutoEllipsis = true;
            _latestValueLabel.Font = new Font("Microsoft YaHei UI", 21F, FontStyle.Bold);
            _latestValueLabel.ForeColor = Color.FromArgb(15, 23, 42);
            _latestValueLabel.Location = new Point(12, 25);
            _latestValueLabel.Name = "_latestValueLabel";
            _latestValueLabel.Size = new Size(280, 34);
            _latestValueLabel.Text = "--";
            _latestValueLabel.TextAlign = ContentAlignment.MiddleLeft;
            latestValueCard.Controls.Add(_latestValueLabel);
            latestValueDetail = new Label();
            latestValueDetail.AutoSize = true;
            latestValueDetail.Font = new Font("Microsoft YaHei UI", 8F);
            latestValueDetail.ForeColor = Color.FromArgb(100, 116, 139);
            latestValueDetail.Location = new Point(12, 62);
            latestValueDetail.Name = "latestValueDetail";
            latestValueDetail.Text = "16 位无符号计数";
            latestValueCard.Controls.Add(latestValueDetail);
            readoutLayout.Controls.Add(latestValueCard, 0, 0);
            sampleCountCard = new Panel();
            sampleCountCard.BackColor = Color.White;
            sampleCountCard.BorderStyle = BorderStyle.None;
            sampleCountCard.Dock = DockStyle.Fill;
            sampleCountCard.Margin = new Padding(4);
            sampleCountCard.Name = "sampleCountCard";
            sampleCountCard.Padding = new Padding(16, 10, 12, 8);
            sampleCountCaption = new Label();
            sampleCountCaption.AutoSize = true;
            sampleCountCaption.Font = new Font("Microsoft YaHei UI", 8.5F);
            sampleCountCaption.ForeColor = Color.FromArgb(100, 116, 139);
            sampleCountCaption.Location = new Point(12, 6);
            sampleCountCaption.Name = "sampleCountCaption";
            sampleCountCaption.Text = "本次连接收到";
            sampleCountCard.Controls.Add(sampleCountCaption);
            _sampleCountLabel = new Label();
            _sampleCountLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            _sampleCountLabel.AutoEllipsis = true;
            _sampleCountLabel.Font = new Font("Microsoft YaHei UI", 21F, FontStyle.Bold);
            _sampleCountLabel.ForeColor = Color.FromArgb(15, 23, 42);
            _sampleCountLabel.Location = new Point(12, 25);
            _sampleCountLabel.Name = "_sampleCountLabel";
            _sampleCountLabel.Size = new Size(280, 34);
            _sampleCountLabel.Text = "0";
            _sampleCountLabel.TextAlign = ContentAlignment.MiddleLeft;
            sampleCountCard.Controls.Add(_sampleCountLabel);
            sampleCountDetail = new Label();
            sampleCountDetail.AutoSize = true;
            sampleCountDetail.Font = new Font("Microsoft YaHei UI", 8F);
            sampleCountDetail.ForeColor = Color.FromArgb(100, 116, 139);
            sampleCountDetail.Location = new Point(12, 62);
            sampleCountDetail.Name = "sampleCountDetail";
            sampleCountDetail.Text = "样本数";
            sampleCountCard.Controls.Add(sampleCountDetail);
            readoutLayout.Controls.Add(sampleCountCard, 1, 0);
            sampleRateCard = new Panel();
            sampleRateCard.BackColor = Color.White;
            sampleRateCard.BorderStyle = BorderStyle.None;
            sampleRateCard.Dock = DockStyle.Fill;
            sampleRateCard.Margin = new Padding(4);
            sampleRateCard.Name = "sampleRateCard";
            sampleRateCard.Padding = new Padding(16, 10, 12, 8);
            sampleRateCardCaption = new Label();
            sampleRateCardCaption.AutoSize = true;
            sampleRateCardCaption.Font = new Font("Microsoft YaHei UI", 8.5F);
            sampleRateCardCaption.ForeColor = Color.FromArgb(100, 116, 139);
            sampleRateCardCaption.Location = new Point(12, 6);
            sampleRateCardCaption.Name = "sampleRateCardCaption";
            sampleRateCardCaption.Text = "采集通道";
            sampleRateCard.Controls.Add(sampleRateCardCaption);
            _sampleRateLabel = new Label();
            _sampleRateLabel.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
            _sampleRateLabel.AutoEllipsis = true;
            _sampleRateLabel.Font = new Font("Microsoft YaHei UI", 21F, FontStyle.Bold);
            _sampleRateLabel.ForeColor = Color.FromArgb(15, 23, 42);
            _sampleRateLabel.Location = new Point(12, 25);
            _sampleRateLabel.Name = "_sampleRateLabel";
            _sampleRateLabel.Size = new Size(280, 34);
            _sampleRateLabel.Text = "CH1 · 50 Hz";
            _sampleRateLabel.TextAlign = ContentAlignment.MiddleLeft;
            sampleRateCard.Controls.Add(_sampleRateLabel);
            sampleRateDetail = new Label();
            sampleRateDetail.AutoSize = true;
            sampleRateDetail.Font = new Font("Microsoft YaHei UI", 8F);
            sampleRateDetail.ForeColor = Color.FromArgb(100, 116, 139);
            sampleRateDetail.Location = new Point(12, 62);
            sampleRateDetail.Name = "sampleRateDetail";
            sampleRateDetail.Text = "设备通道 1";
            sampleRateCard.Controls.Add(sampleRateDetail);
            readoutLayout.Controls.Add(sampleRateCard, 2, 0);
            rootLayout.Controls.Add(readoutLayout, 0, 3);
            chartCard = new Panel();
            chartCard.BackColor = Color.White;
            chartCard.BorderStyle = BorderStyle.None;
            chartCard.Dock = DockStyle.Fill;
            chartCard.Margin = new Padding(0, 4, 0, 4);
            chartCard.Name = "chartCard";
            chartCard.Padding = new Padding(14, 10, 14, 10);
            chartLayout = new TableLayoutPanel();
            chartLayout.ColumnCount = 1;
            chartLayout.Dock = DockStyle.Fill;
            chartLayout.Margin = new Padding(0);
            chartLayout.Name = "chartLayout";
            chartLayout.RowCount = 2;
            chartCard.Controls.Add(chartLayout);
            chartLayout.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            chartLayout.RowStyles.Add(new RowStyle(SizeType.Absolute, 38F));
            chartLayout.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            chartHeader = new TableLayoutPanel();
            chartHeader.ColumnCount = 2;
            chartHeader.Dock = DockStyle.Fill;
            chartHeader.Margin = new Padding(0);
            chartHeader.Name = "chartHeader";
            chartHeader.RowCount = 1;
            chartHeader.ColumnStyles.Add(new ColumnStyle(SizeType.Percent, 100F));
            chartHeader.ColumnStyles.Add(new ColumnStyle(SizeType.AutoSize));
            chartHeader.RowStyles.Add(new RowStyle(SizeType.Percent, 100F));
            chartTitleLabel = new Label();
            chartTitleLabel.Dock = DockStyle.Fill;
            chartTitleLabel.Font = new Font("Microsoft YaHei UI", 10F, FontStyle.Bold);
            chartTitleLabel.ForeColor = Color.FromArgb(15, 23, 42);
            chartTitleLabel.Name = "chartTitleLabel";
            chartTitleLabel.Text = "实时波形";
            chartTitleLabel.TextAlign = ContentAlignment.MiddleLeft;
            chartHeader.Controls.Add(chartTitleLabel, 0, 0);
            chartActions = new FlowLayoutPanel();
            chartActions.AutoSize = true;
            chartActions.Dock = DockStyle.Fill;
            chartActions.FlowDirection = FlowDirection.RightToLeft;
            chartActions.Margin = new Padding(0);
            chartActions.Name = "chartActions";
            chartActions.WrapContents = false;
            _clearButton = new Button();
            _clearButton.BackColor = Color.FromArgb(248, 250, 252);
            _clearButton.Cursor = Cursors.Hand;
            _clearButton.FlatStyle = FlatStyle.Flat;
            _clearButton.Font = new Font("Microsoft YaHei UI", 8.5F, FontStyle.Bold);
            _clearButton.ForeColor = Color.FromArgb(15, 23, 42);
            _clearButton.Margin = new Padding(0, 0, 10, 0);
            _clearButton.Name = "_clearButton";
            _clearButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(226, 232, 240);
            _clearButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            _clearButton.Size = new Size(94, 38);
            _clearButton.TabIndex = 7;
            _clearButton.Text = "清空预览";
            _clearButton.UseVisualStyleBackColor = false;
            chartActions.Controls.Add(_clearButton);
            _clearButton.FlatAppearance.BorderSize = 1;
            _clearButton.Click += ClearButton_Click;
            _exportButton = new Button();
            _exportButton.BackColor = Color.FromArgb(248, 250, 252);
            _exportButton.Cursor = Cursors.Hand;
            _exportButton.FlatStyle = FlatStyle.Flat;
            _exportButton.Font = new Font("Microsoft YaHei UI", 8.5F, FontStyle.Bold);
            _exportButton.ForeColor = Color.FromArgb(15, 23, 42);
            _exportButton.Margin = new Padding(0, 0, 10, 0);
            _exportButton.Name = "_exportButton";
            _exportButton.FlatAppearance.MouseOverBackColor = Color.FromArgb(226, 232, 240);
            _exportButton.FlatAppearance.BorderColor = Color.FromArgb(203, 213, 225);
            _exportButton.Size = new Size(94, 38);
            _exportButton.TabIndex = 6;
            _exportButton.Text = "导出 CSV";
            _exportButton.UseVisualStyleBackColor = false;
            chartActions.Controls.Add(_exportButton);
            _exportButton.FlatAppearance.BorderSize = 1;
            _exportButton.Click += ExportButton_Click;
            _chartStatusLabel = new Label();
            _chartStatusLabel.AutoEllipsis = true;
            _chartStatusLabel.Font = new Font("Microsoft YaHei UI", 8.5F);
            _chartStatusLabel.ForeColor = Color.FromArgb(100, 116, 139);
            _chartStatusLabel.Name = "_chartStatusLabel";
            _chartStatusLabel.Size = new Size(250, 38);
            _chartStatusLabel.Text = "显示最近 1,000 个原始采样点";
            _chartStatusLabel.TextAlign = ContentAlignment.MiddleRight;
            chartActions.Controls.Add(_chartStatusLabel);
            chartHeader.Controls.Add(chartActions, 1, 0);
            chartLayout.Controls.Add(chartHeader, 0, 0);
            _waveformPreview = new WaveformPreviewControl();
            _waveformPreview.Dock = DockStyle.Fill;
            _waveformPreview.Margin = new Padding(0);
            _waveformPreview.MinimumSize = new Size(300, 150);
            _waveformPreview.Name = "_waveformPreview";
            _waveformPreview.UnitText = "count";
            channelTabs = new TabControl();
            channelTabs.Dock = DockStyle.Fill;
            channelTabs.Name = "channelTabs";
            channelTabs.ItemSize = new Size(60, 26);
            channelOneTab = new TabPage("CH1");
            channelOneTab.Name = "channelOneTab";
            channelOneTab.Controls.Add(_waveformPreview);
            channelTabs.TabPages.Add(channelOneTab);
            channel2Tab = new TabPage("CH2");
            channel2Tab.Name = "channel2Tab";
            channel2Notice = new Label();
            channel2Notice.Dock = DockStyle.Fill;
            channel2Notice.Font = new Font("Microsoft YaHei UI", 11F);
            channel2Notice.ForeColor = Color.FromArgb(100, 116, 139);
            channel2Notice.Name = "channel2Notice";
            channel2Notice.Text = "CH2 的设备帧协议待确认，暂无独立波形。";
            channel2Notice.TextAlign = ContentAlignment.MiddleCenter;
            channel2Tab.Controls.Add(channel2Notice);
            channelTabs.TabPages.Add(channel2Tab);
            channel3Tab = new TabPage("CH3");
            channel3Tab.Name = "channel3Tab";
            channel3Notice = new Label();
            channel3Notice.Dock = DockStyle.Fill;
            channel3Notice.Font = new Font("Microsoft YaHei UI", 11F);
            channel3Notice.ForeColor = Color.FromArgb(100, 116, 139);
            channel3Notice.Name = "channel3Notice";
            channel3Notice.Text = "CH3 的设备帧协议待确认，暂无独立波形。";
            channel3Notice.TextAlign = ContentAlignment.MiddleCenter;
            channel3Tab.Controls.Add(channel3Notice);
            channelTabs.TabPages.Add(channel3Tab);
            channel4Tab = new TabPage("CH4");
            channel4Tab.Name = "channel4Tab";
            channel4Notice = new Label();
            channel4Notice.Dock = DockStyle.Fill;
            channel4Notice.Font = new Font("Microsoft YaHei UI", 11F);
            channel4Notice.ForeColor = Color.FromArgb(100, 116, 139);
            channel4Notice.Name = "channel4Notice";
            channel4Notice.Text = "CH4 的设备帧协议待确认，暂无独立波形。";
            channel4Notice.TextAlign = ContentAlignment.MiddleCenter;
            channel4Tab.Controls.Add(channel4Notice);
            channelTabs.TabPages.Add(channel4Tab);
            channel5Tab = new TabPage("CH5");
            channel5Tab.Name = "channel5Tab";
            channel5Notice = new Label();
            channel5Notice.Dock = DockStyle.Fill;
            channel5Notice.Font = new Font("Microsoft YaHei UI", 11F);
            channel5Notice.ForeColor = Color.FromArgb(100, 116, 139);
            channel5Notice.Name = "channel5Notice";
            channel5Notice.Text = "CH5 的设备帧协议待确认，暂无独立波形。";
            channel5Notice.TextAlign = ContentAlignment.MiddleCenter;
            channel5Tab.Controls.Add(channel5Notice);
            channelTabs.TabPages.Add(channel5Tab);
            channel6Tab = new TabPage("CH6");
            channel6Tab.Name = "channel6Tab";
            channel6Notice = new Label();
            channel6Notice.Dock = DockStyle.Fill;
            channel6Notice.Font = new Font("Microsoft YaHei UI", 11F);
            channel6Notice.ForeColor = Color.FromArgb(100, 116, 139);
            channel6Notice.Name = "channel6Notice";
            channel6Notice.Text = "CH6 的设备帧协议待确认，暂无独立波形。";
            channel6Notice.TextAlign = ContentAlignment.MiddleCenter;
            channel6Tab.Controls.Add(channel6Notice);
            channelTabs.TabPages.Add(channel6Tab);
            chartLayout.Controls.Add(channelTabs, 0, 1);
            rootLayout.Controls.Add(chartCard, 0, 4);
            Font = new Font("Microsoft YaHei UI", 9F);
            AutoScaleDimensions = new SizeF(96F, 96F);
            AutoScaleMode = AutoScaleMode.Dpi;
            AutoScroll = true;
            AutoScrollMinSize = new Size(860, 600);
            BackColor = Color.FromArgb(241, 245, 249);
            ForeColor = Color.FromArgb(15, 23, 42);
            pagePanel.Name = "pagePanel";
            pagePanel.Dock = DockStyle.Fill;
            pagePanel.Controls.Add(rootLayout);
            Name = "Wave_Height_Meter";
            Controls.Add(pagePanel);
            Size = new Size(1104, 606);
            ResumeLayout(false);
        }

        private TableLayoutPanel rootLayout;
        private Panel headerPanel;
        private Label titleLabel;
        private Label subtitleLabel;
        private Panel connectionCard;
        private TableLayoutPanel connectionLayout;
        private FlowLayoutPanel connectionSettings;
        private Panel ipField;
        private Label ipCaption;
        private TextBox _ipAddressInput;
        private Panel portField;
        private Label portCaption;
        private NumericUpDown _portInput;
        private Panel sampleRateField;
        private Label sampleRateCaption;
        private NumericUpDown _sampleRateInput;
        private Panel sampleLimitField;
        private Label sampleLimitCaption;
        private NumericUpDown _sampleLimitInput;
        private Button _connectButton;
        private Button _disconnectButton;
        private Button _saveSettingsButton;
        private Panel connectionStatusPanel;
        private Label connectionStatusCaption;
        private Label _connectionStatusLabel;
        private FlowLayoutPanel channelStatusPanel;
        private CheckBox channel1Selector;
        private CheckBox channel2Selector;
        private CheckBox channel3Selector;
        private CheckBox channel4Selector;
        private CheckBox channel5Selector;
        private CheckBox channel6Selector;
        private TableLayoutPanel readoutLayout;
        private Panel latestValueCard;
        private Label latestValueCaption;
        private Label _latestValueLabel;
        private Label latestValueDetail;
        private Panel sampleCountCard;
        private Label sampleCountCaption;
        private Label _sampleCountLabel;
        private Label sampleCountDetail;
        private Panel sampleRateCard;
        private Label sampleRateCardCaption;
        private Label _sampleRateLabel;
        private Label sampleRateDetail;
        private Panel chartCard;
        private TableLayoutPanel chartLayout;
        private TableLayoutPanel chartHeader;
        private Label chartTitleLabel;
        private FlowLayoutPanel chartActions;
        private Button _clearButton;
        private Button _exportButton;
        private Label _chartStatusLabel;
        private WaveformPreviewControl _waveformPreview;
        private TabControl channelTabs;
        private TabPage channelOneTab;
        private TabPage channel2Tab;
        private Label channel2Notice;
        private TabPage channel3Tab;
        private Label channel3Notice;
        private TabPage channel4Tab;
        private Label channel4Notice;
        private TabPage channel5Tab;
        private Label channel5Notice;
        private TabPage channel6Tab;
        private Label channel6Notice;
    }
}
