namespace Page_switching.panel
{
    partial class WaveAnalysisPage
    {
        private System.Windows.Forms.Panel pagePanel;

        private System.ComponentModel.IContainer components = null;
        private System.Windows.Forms.TableLayoutPanel root;
        private System.Windows.Forms.Label title;
        private System.Windows.Forms.FlowLayoutPanel options;
        private System.Windows.Forms.TableLayoutPanel body;
        private System.Windows.Forms.Label status;
        private System.Windows.Forms.TextBox inputPath;
        private System.Windows.Forms.Button browseButton;
        private System.Windows.Forms.NumericUpDown channelInput;
        private System.Windows.Forms.ComboBox unitInput;
        private System.Windows.Forms.NumericUpDown rateInput;
        private System.Windows.Forms.NumericUpDown heightInput;
        private System.Windows.Forms.NumericUpDown periodInput;
        private System.Windows.Forms.NumericUpDown gammaInput;
        private System.Windows.Forms.ComboBox spectrumInput;
        private System.Windows.Forms.NumericUpDown passesInput;
        private System.Windows.Forms.NumericUpDown pointsInput;
        private System.Windows.Forms.Button analyzeButton;
        private System.Windows.Forms.Button exportSpectrumButton;
        private System.Windows.Forms.Button exportElementsButton;
        private System.Windows.Forms.Label caption_inputPath;
        private System.Windows.Forms.Label caption_channelInput;
        private System.Windows.Forms.Label caption_unitInput;
        private System.Windows.Forms.Label caption_rateInput;
        private System.Windows.Forms.Label caption_heightInput;
        private System.Windows.Forms.Label caption_periodInput;
        private System.Windows.Forms.Label caption_gammaInput;
        private System.Windows.Forms.Label caption_spectrumInput;
        private System.Windows.Forms.Label caption_passesInput;
        private System.Windows.Forms.Label caption_pointsInput;
        private Page_switching.ComparisonPlotControl plot;
        private System.Windows.Forms.DataGridView elements;
        private System.Windows.Forms.DataGridViewTextBoxColumn elementColumn;
        private System.Windows.Forms.DataGridViewTextBoxColumn valueColumn;
        private System.Windows.Forms.ComboBox methodInput;
        private System.Windows.Forms.NumericUpDown depthInput;
        private System.Windows.Forms.Label depthCaption;
        private System.Windows.Forms.Label methodCaption;
        private System.Windows.Forms.Button importResultsButton;

        protected override void Dispose(bool disposing)
        {
            if (disposing) components?.Dispose();
            base.Dispose(disposing);
        }

        // 使用标准设计器语句，布局完整保留在 Designer 中。
        private void InitializeComponent()
        {
            this.pagePanel = new System.Windows.Forms.Panel();
            this.components = new System.ComponentModel.Container();
            this.root = new System.Windows.Forms.TableLayoutPanel();
            this.title = new System.Windows.Forms.Label();
            this.options = new System.Windows.Forms.FlowLayoutPanel();
            this.body = new System.Windows.Forms.TableLayoutPanel();
            this.status = new System.Windows.Forms.Label();
            this.inputPath = new System.Windows.Forms.TextBox();
            this.browseButton = new System.Windows.Forms.Button();
            this.channelInput = new System.Windows.Forms.NumericUpDown();
            this.unitInput = new System.Windows.Forms.ComboBox();
            this.rateInput = new System.Windows.Forms.NumericUpDown();
            this.heightInput = new System.Windows.Forms.NumericUpDown();
            this.periodInput = new System.Windows.Forms.NumericUpDown();
            this.gammaInput = new System.Windows.Forms.NumericUpDown();
            this.spectrumInput = new System.Windows.Forms.ComboBox();
            this.passesInput = new System.Windows.Forms.NumericUpDown();
            this.pointsInput = new System.Windows.Forms.NumericUpDown();
            this.analyzeButton = new System.Windows.Forms.Button();
            this.exportSpectrumButton = new System.Windows.Forms.Button();
            this.exportElementsButton = new System.Windows.Forms.Button();
            this.caption_inputPath = new System.Windows.Forms.Label();
            this.caption_channelInput = new System.Windows.Forms.Label();
            this.caption_unitInput = new System.Windows.Forms.Label();
            this.caption_rateInput = new System.Windows.Forms.Label();
            this.caption_heightInput = new System.Windows.Forms.Label();
            this.caption_periodInput = new System.Windows.Forms.Label();
            this.caption_gammaInput = new System.Windows.Forms.Label();
            this.caption_spectrumInput = new System.Windows.Forms.Label();
            this.caption_passesInput = new System.Windows.Forms.Label();
            this.caption_pointsInput = new System.Windows.Forms.Label();
            this.plot = new Page_switching.ComparisonPlotControl();
            this.elements = new System.Windows.Forms.DataGridView();
            this.elementColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.valueColumn = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.methodInput = new System.Windows.Forms.ComboBox();
            this.depthInput = new System.Windows.Forms.NumericUpDown();
            this.depthCaption = new System.Windows.Forms.Label();
            this.methodCaption = new System.Windows.Forms.Label();
            this.importResultsButton = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)this.channelInput).BeginInit();
            ((System.ComponentModel.ISupportInitialize)this.rateInput).BeginInit();
            ((System.ComponentModel.ISupportInitialize)this.heightInput).BeginInit();
            ((System.ComponentModel.ISupportInitialize)this.periodInput).BeginInit();
            ((System.ComponentModel.ISupportInitialize)this.gammaInput).BeginInit();
            ((System.ComponentModel.ISupportInitialize)this.passesInput).BeginInit();
            ((System.ComponentModel.ISupportInitialize)this.pointsInput).BeginInit();
            ((System.ComponentModel.ISupportInitialize)this.elements).BeginInit();
            ((System.ComponentModel.ISupportInitialize)this.depthInput).BeginInit();
            this.SuspendLayout();
            this.root.SuspendLayout();
            this.options.SuspendLayout();
            this.body.SuspendLayout();
            this.root.Name = "root";
            this.title.Name = "title";
            this.options.Name = "options";
            this.body.Name = "body";
            this.status.Name = "status";
            this.inputPath.Name = "inputPath";
            this.browseButton.Name = "browseButton";
            this.channelInput.Name = "channelInput";
            this.unitInput.Name = "unitInput";
            this.rateInput.Name = "rateInput";
            this.heightInput.Name = "heightInput";
            this.periodInput.Name = "periodInput";
            this.gammaInput.Name = "gammaInput";
            this.spectrumInput.Name = "spectrumInput";
            this.passesInput.Name = "passesInput";
            this.pointsInput.Name = "pointsInput";
            this.analyzeButton.Name = "analyzeButton";
            this.exportSpectrumButton.Name = "exportSpectrumButton";
            this.exportElementsButton.Name = "exportElementsButton";
            this.caption_inputPath.Name = "caption_inputPath";
            this.caption_channelInput.Name = "caption_channelInput";
            this.caption_unitInput.Name = "caption_unitInput";
            this.caption_rateInput.Name = "caption_rateInput";
            this.caption_heightInput.Name = "caption_heightInput";
            this.caption_periodInput.Name = "caption_periodInput";
            this.caption_gammaInput.Name = "caption_gammaInput";
            this.caption_spectrumInput.Name = "caption_spectrumInput";
            this.caption_passesInput.Name = "caption_passesInput";
            this.caption_pointsInput.Name = "caption_pointsInput";
            this.plot.Name = "plot";
            this.elements.Name = "elements";
            this.root.Dock = System.Windows.Forms.DockStyle.Fill;
            this.root.Padding = new System.Windows.Forms.Padding(16);
            this.root.ColumnCount = 1;
            this.root.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.root.RowCount = 4;
            this.root.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 44F));
            this.root.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 220F));
            this.root.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.root.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 58F));
            this.root.BackColor = System.Drawing.Color.FromArgb(241, 245, 249);
            this.root.Controls.Add(this.title, 0, 0);
            this.root.Controls.Add(this.options, 0, 1);
            this.root.Controls.Add(this.body, 0, 2);
            this.root.Controls.Add(this.status, 0, 3);
            this.title.Text = "波浪统计与频谱对比";
            this.title.Font = new System.Drawing.Font("Microsoft YaHei UI", 16F, System.Drawing.FontStyle.Bold);
            this.title.Dock = System.Windows.Forms.DockStyle.Fill;
            this.options.Dock = System.Windows.Forms.DockStyle.Fill;
            this.options.BackColor = System.Drawing.Color.White;
            this.options.Padding = new System.Windows.Forms.Padding(8);
            this.options.AutoScroll = true;
            this.options.WrapContents = true;
            this.caption_inputPath.Text = "实测文件";
            this.caption_inputPath.AutoSize = true;
            this.caption_inputPath.Margin = new System.Windows.Forms.Padding(6, 9, 3, 3);
            this.options.Controls.Add(this.caption_inputPath);
            this.inputPath.Margin = new System.Windows.Forms.Padding(3, 3, 8, 8);
            this.inputPath.Width = 410;
            this.inputPath.Text = "";
            this.inputPath.ReadOnly = true;
            this.inputPath.BackColor = System.Drawing.Color.White;
            this.inputPath.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.options.Controls.Add(this.inputPath);
            this.options.SetFlowBreak(this.inputPath, false);
            this.browseButton.Margin = new System.Windows.Forms.Padding(3, 3, 8, 8);
            this.browseButton.Text = "选择文件";
            this.browseButton.Size = new System.Drawing.Size(125, 32);
            this.browseButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.browseButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(203, 213, 225);
            this.browseButton.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this.options.Controls.Add(this.browseButton);
            this.caption_channelInput.Text = "通道";
            this.caption_channelInput.AutoSize = true;
            this.caption_channelInput.Margin = new System.Windows.Forms.Padding(6, 9, 3, 3);
            this.options.Controls.Add(this.caption_channelInput);
            this.channelInput.Margin = new System.Windows.Forms.Padding(3, 3, 8, 8);
            this.channelInput.Width = 78;
            this.channelInput.Maximum = 6M;
            this.channelInput.Minimum = 1M;
            this.channelInput.DecimalPlaces = 0;
            this.channelInput.Increment = 1M;
            this.channelInput.Value = 1M;
            this.options.Controls.Add(this.channelInput);
            this.caption_unitInput.Text = "旧文件单位";
            this.caption_unitInput.AutoSize = true;
            this.caption_unitInput.Margin = new System.Windows.Forms.Padding(6, 9, 3, 3);
            this.options.Controls.Add(this.caption_unitInput);
            this.unitInput.Margin = new System.Windows.Forms.Padding(3, 3, 8, 8);
            this.unitInput.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.unitInput.Width = 135;
            this.unitInput.Items.AddRange(new object[] { "mm", "m" });
            this.unitInput.SelectedIndex = 0;
            this.options.Controls.Add(this.unitInput);
            this.caption_rateInput.Text = "CSV频率(Hz)";
            this.caption_rateInput.AutoSize = true;
            this.caption_rateInput.Margin = new System.Windows.Forms.Padding(6, 9, 3, 3);
            this.options.Controls.Add(this.caption_rateInput);
            this.rateInput.Margin = new System.Windows.Forms.Padding(3, 3, 8, 8);
            this.rateInput.Width = 78;
            this.rateInput.Maximum = 1000M;
            this.rateInput.Minimum = 1M;
            this.rateInput.DecimalPlaces = 2;
            this.rateInput.Increment = 0.01M;
            this.rateInput.Value = 50M;
            this.options.Controls.Add(this.rateInput);
            this.caption_heightInput.Text = "理论波高(m)";
            this.caption_heightInput.AutoSize = true;
            this.caption_heightInput.Margin = new System.Windows.Forms.Padding(6, 9, 3, 3);
            this.options.Controls.Add(this.caption_heightInput);
            this.heightInput.Margin = new System.Windows.Forms.Padding(3, 3, 8, 8);
            this.heightInput.Width = 78;
            this.heightInput.Maximum = 10M;
            this.heightInput.Minimum = 0.001M;
            this.heightInput.DecimalPlaces = 3;
            this.heightInput.Increment = 0.01M;
            this.heightInput.Value = 0.05M;
            this.options.Controls.Add(this.heightInput);
            this.caption_periodInput.Text = "理论周期(s)";
            this.caption_periodInput.AutoSize = true;
            this.caption_periodInput.Margin = new System.Windows.Forms.Padding(6, 9, 3, 3);
            this.options.Controls.Add(this.caption_periodInput);
            this.periodInput.Margin = new System.Windows.Forms.Padding(3, 3, 8, 8);
            this.periodInput.Width = 78;
            this.periodInput.Maximum = 100M;
            this.periodInput.Minimum = 0.01M;
            this.periodInput.DecimalPlaces = 3;
            this.periodInput.Increment = 0.01M;
            this.periodInput.Value = 1.5M;
            this.options.Controls.Add(this.periodInput);
            this.caption_gammaInput.Text = "谱峰因子";
            this.caption_gammaInput.AutoSize = true;
            this.caption_gammaInput.Margin = new System.Windows.Forms.Padding(6, 9, 3, 3);
            this.options.Controls.Add(this.caption_gammaInput);
            this.gammaInput.Margin = new System.Windows.Forms.Padding(3, 3, 8, 8);
            this.gammaInput.Width = 78;
            this.gammaInput.Maximum = 20M;
            this.gammaInput.Minimum = 0.01M;
            this.gammaInput.DecimalPlaces = 2;
            this.gammaInput.Increment = 0.01M;
            this.gammaInput.Value = 3.3M;
            this.options.Controls.Add(this.gammaInput);
            this.caption_spectrumInput.Text = "理论谱";
            this.caption_spectrumInput.AutoSize = true;
            this.caption_spectrumInput.Margin = new System.Windows.Forms.Padding(6, 9, 3, 3);
            this.options.Controls.Add(this.caption_spectrumInput);
            this.spectrumInput.Margin = new System.Windows.Forms.Padding(3, 3, 8, 8);
            this.spectrumInput.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.spectrumInput.Width = 135;
            this.spectrumInput.Items.AddRange(new object[] { "JONSWAP", "P-M", "B谱", "ITTC", "规范谱", "Scott", "Darbyshire", "Wallops" });
            this.spectrumInput.SelectedIndex = 0;
            this.options.Controls.Add(this.spectrumInput);
            this.caption_passesInput.Text = "光滑次数";
            this.caption_passesInput.AutoSize = true;
            this.caption_passesInput.Margin = new System.Windows.Forms.Padding(6, 9, 3, 3);
            this.options.Controls.Add(this.caption_passesInput);
            this.passesInput.Margin = new System.Windows.Forms.Padding(3, 3, 8, 8);
            this.passesInput.Width = 78;
            this.passesInput.Maximum = 20M;
            this.passesInput.Minimum = 0M;
            this.passesInput.DecimalPlaces = 0;
            this.passesInput.Increment = 1M;
            this.passesInput.Value = 1M;
            this.options.Controls.Add(this.passesInput);
            this.caption_pointsInput.Text = "光滑点数";
            this.caption_pointsInput.AutoSize = true;
            this.caption_pointsInput.Margin = new System.Windows.Forms.Padding(6, 9, 3, 3);
            this.options.Controls.Add(this.caption_pointsInput);
            this.pointsInput.Margin = new System.Windows.Forms.Padding(3, 3, 8, 8);
            this.pointsInput.Width = 78;
            this.pointsInput.Maximum = 101M;
            this.pointsInput.Minimum = 1M;
            this.pointsInput.DecimalPlaces = 0;
            this.pointsInput.Increment = 1M;
            this.pointsInput.Value = 3M;
            this.options.Controls.Add(this.pointsInput);
            this.analyzeButton.Margin = new System.Windows.Forms.Padding(3, 3, 8, 8);
            this.analyzeButton.Text = "统计分析";
            this.analyzeButton.Size = new System.Drawing.Size(125, 32);
            this.analyzeButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.analyzeButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(203, 213, 225);
            this.analyzeButton.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this.analyzeButton.BackColor = System.Drawing.Color.FromArgb(29, 78, 216);
            this.analyzeButton.ForeColor = System.Drawing.Color.White;
            this.options.Controls.Add(this.analyzeButton);
            this.exportSpectrumButton.Margin = new System.Windows.Forms.Padding(3, 3, 8, 8);
            this.exportSpectrumButton.Text = "导出频谱";
            this.exportSpectrumButton.Size = new System.Drawing.Size(125, 32);
            this.exportSpectrumButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.exportSpectrumButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(203, 213, 225);
            this.exportSpectrumButton.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this.options.Controls.Add(this.exportSpectrumButton);
            this.exportElementsButton.Margin = new System.Windows.Forms.Padding(3, 3, 8, 8);
            this.exportElementsButton.Text = "导出波浪要素";
            this.exportElementsButton.Size = new System.Drawing.Size(125, 32);
            this.exportElementsButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.exportElementsButton.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(203, 213, 225);
            this.exportElementsButton.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this.options.Controls.Add(this.exportElementsButton);
            this.options.SetFlowBreak(this.exportElementsButton, true);
            this.exportSpectrumButton.Enabled = false;
            this.exportElementsButton.Enabled = false;
            this.options.SetFlowBreak(this.browseButton, true);
            this.methodCaption.Text = "分析方式";
            this.methodCaption.AutoSize = true;
            this.methodCaption.Margin = new System.Windows.Forms.Padding(6, 9, 3, 3);
            this.methodCaption.Name = "methodCaption";
            this.methodInput.Name = "methodInput";
            this.methodInput.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.methodInput.Width = 180;
            this.methodInput.Items.AddRange(new object[] { "内置FFT", "旧WaveTJU程序" });
            this.methodInput.SelectedIndex = 0;
            this.methodInput.Margin = new System.Windows.Forms.Padding(3, 3, 8, 8);
            this.depthCaption.Text = "水深(m)";
            this.depthCaption.AutoSize = true;
            this.depthCaption.Margin = new System.Windows.Forms.Padding(6, 9, 3, 3);
            this.depthCaption.Name = "depthCaption";
            this.depthInput.Name = "depthInput";
            this.depthInput.Maximum = 100M;
            this.depthInput.Minimum = 0.001M;
            this.depthInput.DecimalPlaces = 3;
            this.depthInput.Value = 0.6M;
            this.depthInput.Width = 78;
            this.importResultsButton.Name = "importResultsButton";
            this.importResultsButton.Text = "导入旧分析结果";
            this.importResultsButton.Size = new System.Drawing.Size(140, 32);
            this.importResultsButton.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.importResultsButton.BackColor = System.Drawing.Color.FromArgb(248, 250, 252);
            this.options.Controls.Add(this.methodCaption);
            this.options.Controls.Add(this.methodInput);
            this.options.Controls.Add(this.depthCaption);
            this.options.Controls.Add(this.depthInput);
            this.options.Controls.Add(this.importResultsButton);
            this.body.Dock = System.Windows.Forms.DockStyle.Fill;
            this.body.ColumnCount = 2;
            this.body.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 70F));
            this.body.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 30F));
            this.body.RowCount = 1;
            this.body.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.plot.Dock = System.Windows.Forms.DockStyle.Fill;
            this.plot.MinimumSize = new System.Drawing.Size(300, 180);
            this.body.Controls.Add(this.plot, 0, 0);
            this.elements.Dock = System.Windows.Forms.DockStyle.Fill;
            this.elements.AllowUserToAddRows = false;
            this.elements.AllowUserToDeleteRows = false;
            this.elements.ReadOnly = true;
            this.elements.RowHeadersVisible = false;
            this.elements.BackgroundColor = System.Drawing.Color.White;
            this.elements.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.elements.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.elements.EnableHeadersVisualStyles = false;
            this.elements.ColumnHeadersDefaultCellStyle.BackColor = System.Drawing.Color.FromArgb(241, 245, 249);
            this.elements.DefaultCellStyle.SelectionBackColor = System.Drawing.Color.FromArgb(219, 234, 254);
            this.elements.DefaultCellStyle.SelectionForeColor = System.Drawing.Color.FromArgb(15, 23, 42);
            this.elementColumn.Name = "element";
            this.elementColumn.HeaderText = "要素";
            this.valueColumn.Name = "value";
            this.valueColumn.HeaderText = "值";
            this.elements.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] { this.elementColumn, this.valueColumn });
            this.body.Controls.Add(this.elements, 1, 0);
            this.status.Text = "本地会话采用记录的频率；外部采集CSV采用上方频率。旧文件单位需与原标定单位一致。";
            this.status.Dock = System.Windows.Forms.DockStyle.Fill;
            this.status.AutoEllipsis = true;
            this.status.ForeColor = System.Drawing.Color.FromArgb(71, 85, 105);
            this.Font = new System.Drawing.Font("Microsoft YaHei UI", 9F);
            this.AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Dpi;
            this.AutoScroll = true;
            this.AutoScrollMinSize = new System.Drawing.Size(1000, 580);
            this.Size = new System.Drawing.Size(1104, 606);
            this.pagePanel.Location = new System.Drawing.Point(0, 0);
            this.pagePanel.Size = new System.Drawing.Size(1104, 606);
            this.root.Location = new System.Drawing.Point(0, 0);
            this.root.Size = new System.Drawing.Size(1104, 606);
            this.pagePanel.Name = "pagePanel";
            this.pagePanel.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pagePanel.Controls.Add(this.root);
            this.Name = "WaveAnalysisPage";
            this.Controls.Add(this.pagePanel);
            this.body.ResumeLayout(false);
            this.options.ResumeLayout(false);
            this.options.PerformLayout();
            this.root.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)this.channelInput).EndInit();
            ((System.ComponentModel.ISupportInitialize)this.rateInput).EndInit();
            ((System.ComponentModel.ISupportInitialize)this.heightInput).EndInit();
            ((System.ComponentModel.ISupportInitialize)this.periodInput).EndInit();
            ((System.ComponentModel.ISupportInitialize)this.gammaInput).EndInit();
            ((System.ComponentModel.ISupportInitialize)this.passesInput).EndInit();
            ((System.ComponentModel.ISupportInitialize)this.pointsInput).EndInit();
            ((System.ComponentModel.ISupportInitialize)this.elements).EndInit();
            ((System.ComponentModel.ISupportInitialize)this.depthInput).EndInit();
            this.ResumeLayout(false);
        }
    }
}
